stackrox/collector

.circleci/config.yml, .circleci/images/100-push-images.sh, .circleci/images/70-build-collector-slim-and-base-images.sh, .circleci/images/80-build-collector-latest-images.sh
Now that StackRox is open source 🎉 , there are a number of other repos and processes that depend on images being found under `quay.io/stackrox-io`. This PR pushes collector images there also. At some future point, it should be possible to remove the private docker.io/stackrox and quay.io/rhacs-eng registries but that would probably break other workflows and processes, so for now the change is yet another repo. (Which entails a somewhat kludgey 2nd login to quay.io in 100-push-images.sh).
CI is sufficient + validate that images appear at quay.io/stackrox-io.
=> Push images to the public registry

.gitmodules
Due to a bug in GitPython (used by CPaaS), submodules having a `main` branch are not properly cloned. This PR adds the `branch` value to every submodule in `.gitmodules` which seems to workaround this issue.
Regular CI run should be enough.
=> Specify main/master branch for submodules

.circleci/config.yml, .circleci/kernels/build-modules.sh, kernel-modules/build/Dockerfile, kernel-modules/build/Dockerfile.fc36, kernel-modules/build/Dockerfile.hirsute, kernel-modules/build/Dockerfile.linuxkit, kernel-modules/build/Dockerfile.modern, kernel-modules/build/Dockerfile.oracle, kernel-modules/build/Dockerfile.redhat, kernel-modules/build/build-kos, kernel-modules/build/build-wrapper.sh, kernel-modules/dockerized/Dockerfile
This PR refactors some actions previously executed by the drivers compilation script into a separate wrapper script. This is done in order to allow builds done in the RH infrastructure to use a separate script for setting up the environment, while still maintaining most of the build logic in a common script executed by both infrastructures.
Building of drivers should keep working after the changes, so running CI with `build-legacy-probes`, `no-cache` and `dockerized-no-cache` should be enough.
=> Make necessary changes for compatibility with cPaaS

.circleci/builder/save-collector-builder-image.sh, .circleci/config.yml
For building open sourced StackRox, builder image has to be pushed to
the public quay as well. Do this similarly to #644.
CI results are sufficient.
=> Push builder image to quay

.circleci/config.yml, .circleci/kernels/10-determine-tasks-for-current-shard.sh, .circleci/safe-halt.sh
A few instances of CI has been failing when halting with a message stating that the command `circleci` is not found, this PR attempts to mitigate that error by wrapping the `circleci step halt` instruction in a script that retries it a few times.
The `circleci` command has also been replaced by `circleci-agent`, as described [here](https://discuss.circleci.com/t/documentation-for-circleci-agent/36594/3), `circleci step` is indirectly handled by `circleci-agent`, so removing the middle man might also help.
I've run CI 4 times and no error on commands not being found have showed up.
=> Check 'circleci' command is available before halt

.circleci/config.yml
The CI step seems to have been removed by accident during some refactoring
=> Re-add update-suppport-package CI step

.circleci/config.yml
The UBI image steps have been failing due to expired credentials, we can disable them while we get this sorted out.
Green CI run is enough.
=> Disable ubi-image CI steps

.circleci/config.yml
Bumps version of the Garden Linux VM used in integration tests to 576.8
=> Bump Garden Linux VM version

collector/container/Dockerfile, collector/container/devel/extract-bundle.sh, collector/container/rhel/extract-bundle.sh, collector/container/rhel/final-step.sh
In order to diminish the potential attack surface for the collector image, the base image for it has been replaced with ubi-minimal.
CI run should be enough.
=> Use UBI minimal as the base for collector image

.circleci/config.yml, kernel-modules/support-packages/01-collector-to-rox-version-map.py, kernel-modules/support-packages/02-fetch-collectors-metadata.sh, kernel-modules/support-packages/05-create-index.py
This PR aims at making support packages for unreleased versions of collector available before a full stackrox release is tagged, which is needed by the downstream release to create a full collector image. Since there is no point in publishing and releasing the support packages to the general public before a stackrox release, these changes make it so the support package is created and uploaded but it won't be listed in https://cdn.stackrox.io/collector/support-packages/index.html. The instructions for managing a release will need to be updated to directly download the support package using `gsutil` + the module version found in `kernel-modules/MODULE_VERSION`
In order to properly test the logic in this PR I created the `99.99.99` tag which uses the `2.0.0` module version, this properly …
=> Append unreleased tags to support packages

.circleci/config.yml
After #674 was merged, a mismatch between the registry to where the dockerized collector image is pushed and the one the integration tests try to pull them from was introduced. This PR solves this mismatch.
You can see this failure happening in #673. ([CI run](https://app.circleci.com/pipelines/github/stackrox/collector/8768/workflows/c862dd5b-3cff-4e83-ae4b-fbca87d54527))
=> Fix dockerized tests

kernel-modules/support-packages/04-create-support-packages.sh, kernel-modules/support-packages/05-create-index.py, kernel-modules/support-packages/README, kernel-modules/support-packages/templates/index.html
Added a small step after creating the support package to have the sha256 checksum for said files to be output into an accompanying file with the same name and the `.sha256` extension. Content of the file looks like this:
```
130bfe6e3c95e924675714ac6cd31c7466b241fd27101bdaadd7ef3fb3138455  support-pkg-b6745d-latest.zip
```
So downloading it in the same directory as the support package and running `sha256sum -c support-pkg-b6745d-latest.zip.sha256` directly validates the file.
The checksum will also be added to the published index of packages for interested parties to be able to verify the contents of them.
=> ROX-10044: Add SHA256 checksum to support packages

.circleci/kernels/get-builder-flavor.sh, .circleci/test-scripts/get-builder-flavor/TestInput.txt
A 5.17.6 kernel for Fedora 34 is failing to compile because of missing the compiler flag `-mharden-sls`.  We had a similar issue that lead us to implement the `fc36` builder in #621, so bumping kernels 5.17.6+ for Fedora 34 to use this same builder should solve the issue.
Green CI is enough.
=> Bump 5.17.6+ Fedora 34 kernel to build on fc36

.circleci/config.yml, .circleci/test-scripts/baseline/compare-and-update-baseline.sh, .circleci/test-scripts/baseline/main.py
Version 22.04 is the next LTS release for Ubuntu, this PR bumps the previous short term support VMs used in integration tests to this version instead.
=> Bump Ubuntu VMs to 22.04 LTS in tests

collector/lib/ConnTracker.h, collector/test/ConnTrackerTest.cpp, integration-tests/integration_test.go
Fix bug in afterglow where connections are not cleared from old_conn_state and are sent multiple times.
See above
=> ROX-10260 - Fix afterglow bug

.circleci/config.yml, .circleci/test-scripts/baseline/format.awk, .circleci/test-scripts/baseline/main.py
Benchmark numbers have high variance, which makes relative overhead vary
significantly as well. Use absolute overhead value numbers, as they seem
more stable.
Local testing with the baseline data, captured so far.
=> Use absolute overhead, not relative

.circleci/config.yml, .circleci/integration-test/10-check-whether-to-run-job.sh
After merging #641, a subset of integration tests is being run on PRs and the `all-integration-tests` label should be used to force the entirety of them to run. However, this label was not working as expected, this PR should fix it.
It also removes the files created from labels in the `test-scripts` CI job, this is to prevent the labels in a PR from interacting and breaking these tests.
=> Run all tests when `all-integration-tests` label is set in PRs

.circleci/config.yml
Bump Garden Linux VM used for testing to 576.9
=> Bump Garden Linux VM to 576.9

.circleci/test-scripts/baseline/compare-and-update-baseline.sh, .circleci/test-scripts/baseline/main.py
Fix updating baseline data in 74324522c . The issue was about `measure` iterator, which was used directly for producing the result. As soon as other operations started to consume the iterator before that, it become empty and the update is not correctly performed.
On the way do cosmetic improvements for the installation process. Baseline requires some dependencies, installed via `pip`. Do this silently to reduce noise.
Local testing.
=> Fix updating baseline data

kernel-modules/BLOCKLIST
The kernels added to the blocklist are failing to compile, they will remain bloked until further research can be done to find a fix for them.
~- [ ] Investigated and inspected CI test results~
=> Block failing kernels

.circleci/kernels/get-builder-flavor.sh, .circleci/test-scripts/get-builder-flavor/TestInput.txt
Kernels for fc34 that had 2 numbers on the patch version were missed in #680, this PR adds those to the bump
~- [ ] Investigated and inspected CI test results~
=> Bump builder for fc34 5.17.10+ kernels

kernel-modules/build/prepare-src
This patch started by adding a missing variable name to an error message, but I also took the liberty of refactoring the check so that is properly prints the variable that caused the error.
The change itself should be pretty transparent, only the prepare sources step will be affected.
=> Small fix on the prepare-src script

.gitmodules, Makefile, builder/Dockerfile, builder/build/build-ubi-dependencies.sh, builder/install/20-googletest.sh, builder/install/install-dependencies.sh, collector/container/Dockerfile.ubi
The UBI image used to depend on the gmock RPM for building tests.
This one is rather old and has only deprecated MOCK_METHODx macros.
We update the build to use a newer gtest from a submodule.
=> ROX-11725 update googletest for ubi

.openshift-ci/drivers/pre-build.Dockerfile
The root image on OSCI is currently running with user `circleci` and interfering with the driver's `pre-build` stage, this PR forces the stage to build using the `root` user
Rehearsed on openshift/release#29021
=> Follow up to drivers build

collector/lib/CollectorService.cpp, collector/lib/ConnScraper.h, collector/lib/DuplexGRPC.h, collector/lib/NetworkConnectionInfoServiceComm.cpp, collector/lib/NetworkConnectionInfoServiceComm.h, collector/lib/NetworkStatusNotifier.cpp, collector/lib/NetworkStatusNotifier.h, collector/lib/SignalServiceClient.h, collector/proto/CMakeLists.txt, collector/test/NetworkStatusNotifierTest.cpp
In order to test the NetworkConnectionInfoService, we need to mock its dependencies:
* the connection scrapper
* the connection tracker
* the "upstream" channel with Sensor
This first PR is intended to be perfectly isofunctional, and insert those interfaces seamlessly in the call path.
=> ROX-11096 insert interfaces for testability

collector/lib/CollectorConfig.h, collector/test/NetworkStatusNotifierTest.cpp
We want to minimize the risk of regression with the ongoing changes on the collector reporting algorithm.
These tests are able to mock the connection with Sensor down to the level of proto gRPC objects.
=> ROX-17097 Tests to exercise NetworkStatusNotifier at gRPC level.

.openshift-ci/slack/notify.sh
env.sh doesn't exist, pull webhook env directly from the notify script.
Testing is possible via CI logs.
=> Get webhook env directly

.openshift-ci/jobs/push-images/push-images.sh
Add a OSCI job to push collector builder images. See https://github.com/openshift/release/pull/31470
=> ROX-12259 push collector builder images in osci

.openshift-ci/build/Dockerfile.build_collector
This is a sister PR to openshift/release#32169. Changes here are meant to enable a lighter builder image to be built.
CI run should be enough
=> Slim down the collector-builder image

.openshift-ci/jobs/update-support-packages/run.sh, kernel-modules/support-packages/run-all.sh
The link to download support packages is broken. Here is the ticket for that problem https://access.redhat.com/support/cases/#/case/03317606. This fixes that. The problem resulted from the BASE_URL environment variable not being set in VM where the update support packages script is run. This PR sets the value for BASE_URL and passes it to the VM.
See above.
=> Fix support packages

.openshift-ci/scripts/lib.sh
Fixes an issue in secret name identification when attempting to retrieve the secret file from /tmp/secret. This fix simplifies the process a little.  See openshift/release#32025 for the tests/checks
Relying primarily on OSCI
=> Simplifies get_secret_file implementation

.openshift-ci/drivers/scripts/push-drivers.sh, .openshift-ci/scripts/gcloud-init.sh
The soon to be deleted setup-gcp-env script from circleci is now replaced by the gcloud-init script in .openshift-ci. This script is now more flexible to different credentials as required by the caller.
=> Makes push-drivers use gcloud-init script

kernel-modules/container/Dockerfile
Adds an extra layer for the kernel drivers in the collector full image.
=> Add an extra layer for kernels to the collector full image

.pre-commit-config.yaml, Makefile
This is no longer needed, since we stopped using CircleCI.
Not much to test, other than the CircleCI pre-commit hook no longer showing up when creating a new commit.
=> Removes the CircleCI pre-commit hook

.circleci/config.yml, .circleci/initjob/30-set-collector-version.sh, collector/lib/ProtoAllocator.h
This is a backport of https://github.com/stackrox/collector/commit/2d2c2221d3ddbe6df140b553fa50eedceb40b9c8 to fix https://github.com/stackrox/collector/issues/838 on the release-3.9.x release branch
- ~~[ ] Added unit tests~~
- ~~[ ] Added integration tests~~
- ~~[ ] Added regression tests~~
=> ROX-12576 3.9.x arena segfault backport

collector/lib/HostInfo.h, collector/test/HostInfoTest.cpp
Disable ebpf probe on s390x until its ready for production use.
ran unit and integration tests
=> disable ebpf on s390x

collector/collector.cpp, collector/lib/CollectorConfig.h
On s390x we are relegated to socketcall wrapping various system calls until we have glibc support--[details](https://sourceware.org/pipermail/libc-alpha/2022-September/142108.html).  We will not filter syscall type so we can receive these syscalls.
Also included patch to read kernel module into memory and insert from there instead of finit_module.
Ran unit and integration tests on s390x and x86
=> Add s390x support--allow socketcall and inserting kernel fix

Makefile, integration-tests/Makefile, integration-tests/collector_manager.go, integration-tests/endpoint.go, integration-tests/integration_test.go
We need integration tests for ConnScraper as we are about to modify it for the "Processes listening on ports" MVP. ConnScraper is able to find open endpoints when Collector starts up (and thus knows about endpoints that were opened before Collector started up), whereas NetworkSignalHandler only knows about endpoints that open after Collector starts up. To test ConnScraper we start an nginx container before launching Collector, and test that we can find the nginx endpoint when scraping is on and that we cannot find the nginx endpoint when scraping is off.
Related to this PR is a change for the mock grpc server. See https://github.com/stackrox/stackrox/pull/3215
Go into the stackrox repo root directory and run the following commands
Checkout the branch of the stackrox …
=> Jv rox 12845 integration tests for connscraper

integration-tests/integration_test.go
Makes it so that TestNetworkFlows checks for endpoints as well as connections. Right now NetworkSignalHandler does not report endpoints, and TestNetworkFlows only checks for connections. Probably someday NetworkSignalHandler will report endpoints. 
See above
=> Jv integration tests for networksignalhandler endpoints

.openshift-ci/build/Dockerfile.cpaas, .openshift-ci/jobs/integration-tests/env.sh, .openshift-ci/jobs/push-images/push-images.sh
Make some minor changes in order to allow for integration tests to run with CPaaS built drivers. In broad strokes the changes are:
- Create a collector image that holds the CPaaS built drivers.
- Adjust the image used for testing depending on whether we want to test upstream drivers or CPaaS drivers.
=> Build a collector image using the CPaaS drivers

integration-tests/executor.go, integration-tests/integration_test.go, integration-tests/retry.go
Add a simple retry function, apply it to the command executor and container launcher. The implementation has few quirks:
* It doesn't use routines, but in case of integration tests it doesn't matter if we would block.
* It has two return arguments with fixed type: string and error. The latter one is required for retry logic, the former seem to be rather limited choice. The reason is that without returning any data except an error the scope of the payload function would have to be much bigger (as nothing has to be returned). At the moment it looks like we mostly return strings anyway, so it feels like a good compromise between full-fledged solution and a quick hack.
TODO
=> Integration tests retry

.openshift-ci/jobs/integration-tests/run-integration-tests.sh
A function has been added to the `run-integration-tests.sh` script for CI environment to be propagated into the tests by exporting environment variables.
The only variable being propagated right now is OFFLINE so that integration tests can be run in offline mode, this function could be extended to other environment variables or PR labels in the future.
=> Add a function for propagating CI environment in integration tests

Makefile, collector/Makefile, collector/connscrape-test/Dockerfile, collector/connscrape-test/connscrape-test.sh, collector/connscrape.cpp, collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/CollectorService.cpp, collector/lib/ConnScraper.cpp, collector/lib/ConnTracker.h, collector/lib/NetworkConnection.cpp, collector/lib/NetworkConnection.h, collector/lib/NetworkStatusNotifier.cpp, collector/lib/NetworkStatusNotifier.h, collector/lib/Process.cpp, collector/lib/Process.h, collector/lib/ProcfsScraper.cpp, collector/lib/ProcfsScraper.h, collector/lib/ProcfsScraper_internal.h, collector/test/ConnScraperTest.cpp, collector/test/ConnTrackerTest.cpp, docs/references.md
Originator process information is added to network endpoint objects sent to Sensor.
This information comes from a ProcessStore which deduplicates process information between endpoints sharing the same originator. Ultimately, the information comes from a new Process scraper.
- ~~[ ] Added integration tests~~
- ~~[ ] Added regression tests~~
=> ROX-13114 add process info to network endpoints

collector/collector.cpp, utilities/lint.sh
Make the `lint.sh` script fail when at least one of the underlying linters fail.
Also fix some small formatting errors that were not being alerted on.
Green CI should be enough.
=> Make 'make linters' fail correctly

collector/lib/HostHeuristics.cpp
Although I wonder if this block shouldn't be removed entirely (after all, why assume Secure Boot if none of the signs thereof could be detected?), at a minimum, this logic should not be applied to other architectures.
=> collector: force ebpf if SecureBoot undetermined only on x86_64

.openshift-ci/build/Dockerfile.cpaas
The additional `/` in the bucket name makes it so `gsutil` fails to properly download drivers into the image.
=> Fix bucket used for cpaas images

integration-tests/collector_manager.go, integration-tests/endpoint.go, integration-tests/integration_test.go, integration-tests/process_originator.go
The ConnScraper integration test which checks endpoint information sent by collector will now check that the endpoint information includes the process originator.
This PR is the parent of https://github.com/stackrox/collector/pull/870
The difference between the two PRs is that this expects the process information to be nil and the other expects to find actual process information.
See above
=> ROX-13015 collector integration tests should check for process info in endpoints

collector/collector.cpp, collector/lib/CollectorService.cpp, collector/lib/CollectorService.h, collector/lib/Control.h, collector/lib/KernelDriver.cpp, collector/lib/KernelDriver.h, collector/lib/NRadix.cpp, collector/lib/Sysdig.h, collector/lib/SysdigService.cpp, collector/lib/SysdigService.h
Refactors SysdigService and CollectorService to centralise the kernel driver insertion logic to better inform start up diagnostics. This also decouples some components within CollectorService.
The kernel driver setup logic is now in a set of classes of its own, and then initialised by the SysdigService. 
Some local testing, but CI should uncover any significant problems with this refactor.
=> ROX-11447: refactor kernel driver start up

collector/collector.cpp, collector/lib/HostHeuristics.cpp, collector/lib/Logging.cpp, collector/lib/Logging.h, collector/lib/SysdigService.cpp
Writes all `FATAL` log messages to [/dev/termination-log](https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/) if that device exists. In k8s, it is used to enrich container status information, and allows us to report better errors through k8s APIs for diagnostics of Collector startup. 
Commands for getting this enriched information:
```bash
$ kubectl describe pod -n stackrox collector-cr2mf
Last State:     Terminated
Reason:       Error
Message:      No suitable kernel object downloaded
Exit Code:    1
Started:      Fri, 21 Oct 2022 11:50:56 +0100
Finished:     Fri, 21 Oct 2022 11:51:25 +0100
$ kubectl get pods -n stackrox collector-cr2mf -o jsonpath='{.status.containerStatuses[].lastState}' | jq .
{
"terminated": {
"containerID": …
```
=> ROX-11447: write fatal log messages to termination log

Makefile, integration-tests/Makefile, integration-tests/integration_test.go, integration-tests/process_originator.go
Disabling ConnScraper tests for sles-12 and ubuntu-2204-lts
CI is sufficient
=> Jv disable tests for failing vms

Makefile, integration-tests/Makefile, integration-tests/container/processes-listening-on-ports/Dockerfile, integration-tests/container/processes-listening-on-ports/Makefile, integration-tests/container/processes-listening-on-ports/process-listening-on-ports.c, integration-tests/endpoint.go, integration-tests/integration_test.go, integration-tests/listen_address.go
Adds a program that opens and closes ports that it is told to open and close. The program reads from a file with simple commands such as "open 8080" and "close 9090". Whenever the program reads a command from the file it deletes it and waits for the file to be recreated with new commands. Integration tests issue commands to this program and expected results are compared to actual results.
=> ROX-13095 endpoint should be reported closed when it is closed by a process

collector/test/HostHeuristicsTest.cpp
As per collector/lib/HostHeuristics.cpp:143 the test is adjusted to account for the ifdef 
Unit tests built and run locally.
=> Fixes TestSecureBootNotDetermined test on Power/Z

.openshift-ci/build/build-collector.sh, .openshift-ci/scripts/lib.sh
When running from PRs, the URL used for driver download gets a `cid=collector` parameter appended to it, this is done for some internal filtering. When we migrated to OSCI, this extra parameter has been added to all versions of collector, it has no functional impact on it, but we should still only add it when it is actually needed.
Testing will need to happen once we merge to master or by removing the `export COLLECTOR_APPEND_CID=true` line altogether.
=> Only append CID on PR builds

ansible/run-integration-tests.yml, ansible/tasks/test-collection-method.yml
This change makes it so if one of the integration test running with eBPF fails, the tests with kernel-modules still executes.
<details>
<summary>Example log of test failing and continuing to run.</summary>
```
PLAY [Create VMs] ******************************************************************************************************************************************
PLAY [Provision VMs] ***************************************************************************************************************************************
PLAY [Run integration tests] *******************************************************************************************************************************
TASK [Gathering Facts] ************************************************************************************************ …
```
=> Catch integration test failures and fail after all variations are done

Makefile, integration-tests/Makefile, integration-tests/integration_test.go, integration-tests/process_originator.go
Adds a test that executes the following command "socat TCP-LISTEN:80,fork STDOUT & socat  TCP-LISTEN:8080,fork STDOUT" and ensure that the container endpoints are reported correctly.
Ran integration tests locally with make integration-tests-socat. Ran CI.
=> Jv rox 13507 collector integration test that opens multiple ports in the same command

kernel-modules/BLOCKLIST
The drivers added to `BLOCKLIST` are currently failing due to a known problem with kernel-packer that breaks the bundles.
=> Exclude broken Debian bundles from driver builds

collector/lib/ProcfsScraper.cpp, integration-tests/integration_test.go
The netns connections file is shared among all the processes living in this netns, so it is incorrect to map PID by using it.
Prior to this fix, all process information attached to an endpoint was the one of the first process in the namespace.
=> ROX-13560 fix: PID from file-descriptors and not netns

Makefile, integration-tests/Makefile, integration-tests/container/processes-listening-on-ports/Dockerfile, integration-tests/container/processes-listening-on-ports/process-listening-on-ports.c, integration-tests/integration_test.go
Adds a test to check that when a process is launched using a symbolic link that the process information and the process information in the endpoint stream match.
CI and ran tests locally.
=> rox-13539 collector integration tests for an executable with symbolic link

kernel-modules/support-packages/04-create-support-packages.sh
This PR just adds a new file: `latest` - to the list of built support packages.
The `latest` file will contain the last build for that kernel module version.
Related to the conversation in Slack: https://srox.slack.com/archives/CFMQ5C2TT/p1669284268331969
**Open question**
- I'm not sure if this file will be properly synced to Google Storage.
- ~~[ ] Added unit tests~~
- ~~[ ] Added integration tests~~
- ~~[ ] Added regression tests~~
I didn't test it. I just made a conclusion from the code about what should be changed. 😞
=> Add latest file to list of support packages

.github/workflows/collector-image.yml, Makefile
This PR adds a GHA workflow for building the `-slim` and `-base` images of collector. We achieve this by making a few checks on what the context of the workflow is, setting a few environment variables and calling `make image` in a pretty similar way to what building the image locally for development is. Once the images are built, they are pushed to out `quay.io` registries to make the available for usage.
--
=> Collector and builder images on GHA

.github/dependabot.yaml
Monitor docker images and update them with @dependabot
Refs: https://github.com/dependabot/feedback/issues/145
=> Keep dockerfiles up to date

.github/workflows/lint.yml, .pre-commit-config.yaml
Very simple workflow for running linters across the codebase, using pre-commit. Notable change is a move from SSH to HTTPS for cloning the pre-commit actions as well as running the hooks only on the diff between a PR and the base branch (usually master, but it is configured for any base branch) 
this has all been successfully tested locally.
=> GHA workflow for linters

.github/drivers/mock-cache.sh, .github/workflows/drivers.yml
This PR makes 2 small changes:
- Properly silences a `gsutil ls` as to not flood logs.
- Ensures the same location is used for pushing drivers and pulling them back down.
CI is enough.
=> More fixes to driver builds on GHA

.github/workflows/drivers.yml
Due to a compatibility issue with OSCI, the fc36 tasks are placed under `/tmp/tasks/fc36/all` when a single builder is needed, but GHA looks for this under `/tmp/tasks/fc36/0/all`, so we simply move the file when needed.
=> Ensure the fc36 builder tasks are in the right path

.github/workflows/drivers.yml, .github/workflows/main.yml, .github/workflows/upload-drivers.yml
By making this change, checking for driver build failures can happen in parallel with the upload.
The check will also not depend on the upload to succeeded to show a build error.
Green CI with `no-cache` should be enough
=> Move the driver upload out of the driver build workflow

.github/workflows/collector-full.yml
When retagging collector slim to full on PRs, the repository needs to be checked out before using the `retag-and-push` action.
Green CI should be enough.
=> Minor fix when retagging collector full on PRs

.github/workflows/integration-tests-vm-type.yml, .github/workflows/main.yml
Add slack notifications for driver build errors and integration tests failures on pushes.
Did some manual testing and alerts are properly showing up in the oncall channel.
=> Add Slack notifications

RELEASED_VERSIONS, RELEASED_VERSIONS.unsupported
The 3.68, 3.69 and 3.70 stackrox versions have already reached EOL, so we should update our supported collector versions to reflect this. Added bonus, the following driver versions will no longer be built for added kernels:
- The last sysdig driver version
- 1.0.0
Support packages for the previous versions will also not be updated anymore.
- Green CI should be enough.
=> Move unsupported versions to RELEASED_VERSIONS.unsupported

ansible/ansible.cfg
By default ansible allows up to 5 forks, which was causing a slow down on tests run on 6 or more VMs. This patch ups the max number of forks to 10.
CI with `all-integration-tests` label should be enough.
=> Allow up to 10 forks of ansible

.github/support-packages/create-metadata-dir.sh, .github/workflows/drivers.yml, .github/workflows/main.yml, .github/workflows/support-packages.yml
This PR adds a workflow for creating and pushing support packages on GHA. The procedure is relatively straight forward, most of the process consists of calling the scripts under `kernel-modules/support-packages` in the right order and with the correct environment variables and parameters set.
=> Support packages on gha

Makefile, integration-tests/Makefile
Removes test-specific targets in favour of auto-generated targets based on output of `go test -list` to make the system a little more scalable to large numbers of tests.
=> Simplifies Makefile targets for testing

Makefile
Running make dev-build no longer works after changes to how make is used to run integration tests. This fixes that.
TestSocat failed in the integration tests for unrelated reasons
See above
=> Jv fix make dev build

.github/workflows/collector-slim.yml, .github/workflows/init.yml, .github/workflows/main.yml, .github/workflows/support-packages.yml
This is the final step for making GHA the official CI solution, OSCI needs to be taken offline first. The PR will remain in draft in order to prevent OSCI from running (GHA jobs trigger regardless of this), once OSCI is disabled we can open and merge this PR directly.
Testing as much of the affected CI jobs as possible through the `build-builder-image` and `no-cache` labels, as well as testing the support-packages. final test will need to happen on the master branch though.
=> Move CI to GHA

.github/workflows/integration-tests-vm-type.yml, .github/workflows/integration-tests.yml
Puts notifications for integration tests one level higher so a notification is sent once instead of for each individual integration test platform.
=> Unifies integration test notifications

integration-tests/suites/socat.go
Fixes a shell escaping problem in the socat test, by simplifying the command into two executions in the socat container.  
Tested locally against RHEL8
=> Fixes shell escaping problem in socat test

integration-tests/Makefile, integration-tests/benchmark_test.go, integration-tests/integration_test.go, integration-tests/suites/benchmark.go
Prevents the benchmarks from running unless specified. They are currently running on master builds, which is slowing down the integration tests and causing some timeout errors.
Tested locally.
=> Moves Benchmark tests behind build tag

kernel-modules/BLOCKLIST, kernel-modules/build/apply-blocklist.py, kernel-modules/dockerized/scripts/get-build-tasks.sh
Some kernels were being blocked from being compiled because GHA applied an additional BLOCKLIST file meant for the now deprecated dockerized build of drivers. This PR makes it so the only BLOCKLIST applied is the one located under `kernel-modules/BLOCKLIST`.
I will create a follow up PR removing the dockerized directory and cleaning up a bit, since we haven't used much of it in the past months.
I've also made it so the list of blocked kernels are output to GHA logs, that way it will be easier for us to spot a missing driver due to the blocklist.
=> Drop dockerized BLOCKLIST

.github/workflows/collector-full.yml, .github/workflows/cpaas-sync-drivers.yml, .github/workflows/cpaas.yml, .github/workflows/cpaas/sync-drivers.yml, .github/workflows/init.yml, .github/workflows/integration-tests-vm-type.yml, .github/workflows/main.yml
This PR adds a new set of GHA workflows that allow for testing the downstream built drivers, as well as uploading those drivers and corresponding support-packages to GCP.
The new `cpaas-sync-drivers` workflow pulls the downstream built drivers image for all supported architectures (x86, ppc64le and s390x), extracts the drivers and support-packages from it and pushes them to GCP.
The `cpaas` workflow is based on existing workflows that are used in the `main` workflow, but taking parameters specific for the new use cases. It creates collector images embedding the downstream drivers into them and tags them with a `-cpaas` suffix. Those images are then used to run integration tests in offline mode in the pertinent VMs (`rhel` and `rhel-sap`).
There are currently 2 ways of triggering these new …
=> Migrate CPaaS related CI to GHA

.openshift-ci/drivers/scripts/drivers-build-failures.sh
When compiling a large number of drivers, sometimes some BPF drivers for kernels that don't support it are reported as failed to build, even though the actual build shows a message stating that it is being skipped. Since we redirect stderr to this file, an empty file would be the same as no error, so we should be ok to ignore it.
I suspect when the driver is skipped there might be some timing issue with the subshell being spawned to run tee, making it so we attempt to delete the file before it is actually created and then the subshell comes up and creates the empty file.
=> Ignore empty driver build failure files

.github/workflows/collector-full.yml
When building the full version of collector on push, tag or schedule events, the newly built drivers should be added to the image too.
No additional testing performed.
=> Restore built drivers on non-pr events

docs/troubleshooting.md
Add a section to the _troubleshooting_ documentation page, with all the counters and timers advertised and a description of what they represent.
=> [doc] List of timers and counters with description

RELEASED_VERSIONS
Automated PR for version 3.73.1 failed, so we are adding it manually. The time stamp is approximated to the creation of the release and tag.
CI is enough
=> Add 3.73.1 to RELEASED_VERSIONS

ansible/Makefile, ansible/group_vars/all.yml, ansible/image-upload.yml
Adds and image-upload ansible playbook to synchronize development Collector image builds with the ansible inventory. Intended primarily as a development tool for those who do not wish to use an intermediary quay repository.
=> Adds image-upload ansible playbook 

collector/lib/CollectorStats.h, collector/lib/Process.cpp, docs/troubleshooting.md
Falco is requested by Process objects to resolve details of the process they represent. This procedure is asynchronous and Process may wait for it to complete.
"process_info_wait" is the time spent waiting (in us)
=> ROX-14201 New timer to track time waiting for process-info

docs/release.md
Update to the release docs after migrating to GHA. Aside from the mandatory cleanup some style changes have been made, namely:
- Use code blocks for shell commands.
- Split long lines.
None needed, since this is docs only 🙂
=> Update release docs

integration-tests/suites/common/collector_manager.go
Updates the mock grpc server image used by the integration tests, to be able to handle a large number of messages. See this PR in stackrox/stackrox https://github.com/stackrox/stackrox/pull/3976 that actually made the change in the grpc server image.
See the testing in this PR https://github.com/stackrox/stackrox/pull/3976
=> Jv update mock grpc server image

ansible/group_vars/all.yml
Self explanatory, bumping the testing VM being used for Garden to latest release.
=> Bump Garden Linux VM to 934.2

.github/workflows/cpaas.yml
This is an extremely simple change that provides a slightly clearer notification message when the downstream nightly workflow fails.
Not much to test, as long as the yaml is valid, functionality is unaffected.
=> Use a clearer message when downstream nightly fails

ansible/ci/group_vars/all.yml, ansible/dev/group_vars/all.yml, ansible/roles/create-all-vms/tasks/main.yml, ansible/roles/create-vm/tasks/main.yml, ansible/roles/destroy-vm/tasks/main.yml
To avoid the case where a zone is unable to accept our VM creation request, this PR changes the ansible logic to loop over a set of available zones, using the first one that succeeds. 
Tested locally, but unable to truly test when a zone fails. I have verified that if the previous execution fails it will continue to try the next zone.
=> Adds zone looping to VM creation

kernel-modules/support-packages/05-create-index.py
Checksum URLs are missing a `/`, so we add it.
=> Fix checksum file URLs for support-packages

collector/lib/ConnTracker.cpp, collector/lib/ConnTracker.h, collector/lib/Hash.h, collector/lib/NetworkConnection.h, collector/lib/NetworkStatusNotifier.cpp, collector/lib/NetworkStatusNotifier.h, collector/lib/Process.cpp, collector/lib/Process.h, collector/lib/ProcfsScraper.cpp, collector/test/ConnTrackerTest.cpp, integration-tests/integration_test.go, integration-tests/suites/duplicate_endpoints.go
In Collector, an endpoint now represents a listening socket with a reference to the process making use of it. When an endpoint is published, however, the process information is stripped down to represent a the name and parameters of this process instead of the precise instance.
This as an impact on the life-cycle of endpoint objects "as seen from the outside". For instance, the same endpoint opened by several processes having the same attributes should appear as a single endpoint.
In order to implement this model, we propose to change the comparison operator used by the ConnTracker when building the normalized list of endpoints.
=> ROX-13628 Create an external representation of endpoints (conntracker)

Makefile, collector/Makefile
The current make target uses individual new calls to make for each step of the build, which means the artifact `container/bin/collector` is incorrectly assumed to have built even when the source files change. Making each step a dependency of the build target means that their dependencies are used as dependencies of `container/bin/collector` and any source changes will trigger a rebuild of those files.
=> Fixes build caching in collector build

collector/lib/ProfilerHandler.cpp, collector/test/NRadixTest.cpp
The fixed warnings are:
```
warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
```
Existing tests should cover the changes.
=> Silence compiler warnings about signedness comparison issues.

Makefile, collector/container/Dockerfile.template, collector/container/devel/final-step.sh
This PR removes the possibility to dynamically change the base image used for the collector image. Originally this allowed us to have a UBI and Ubuntu based images, we then dropped Ubuntu images and started using this to build a development image based on centos stream. Because the devel and prod images are pretty close to each other, I believe it is more beneficial for us to have the image set to the production one so that dependabot can bump it on its own.
The devel image will now be based on ubi-minimal, which means the available packages are somewhat limited, but it is still possible to directly install gdb on it, which is the most important thing we want in it IMO.
=> Remove the dynamic configuration of base image for collector

.github/workflows/drivers.yml, kernel-modules/build/kernel-splitter.py
Minor cleanup, removes some code that was left for compatibility with OSCI.
=> Cleanup remaining OSCI code from kernel-splitter.py

kernel-modules/build/fc36.Dockerfile
Symlink `gcc` to `gcc10-gcc` so that amazon linux kernel modules can be compiled.
=> Add symlink to gcc10-gcc

.editorconfig
The current `.editorconfig` file doesn't set the style for our `.cpp` and `.h` files, which means the indentation is either derived from content (in VSCode), or left untouched (in things like neovim). `clang-format` fixes style problems after editing files, but it is a bit distracting when your editor is trying to use tabs or 4 spaces and getting it mixed up with the existing 2 space indented lines.
Since we already have a `.editorconfig` file in the repo, we might as well configure it to use 2 spaces on `.cpp` and `.h` files found under `collector/` and `collector/lib/`.
This change is purely for editor configuration, no functional changes will occur. That said, the change works as expected on neovim with an `editorconfig` plugin.
=> Use the proper indent configuration for .cpp and .h files

ansible/group_vars/all.yml
Self explanatory, bumping the Garden Linux VM version to the latest available.
=> Bump Garden Linux VM to 934.5

collector/lib/DriverCandidates.cpp, collector/test/DriverCandidatesTest.cpp, collector/test/UtilityTest.cpp
A quick change to the `DriverCandidate` constructor in #1040 before merging resulted in the kernel version being used as the relative path for some candidates. This PR fixes that small bug.
=> Fix kernel versions being used as relative path

.gitignore, Makefile, collector/.gitignore, collector/Makefile, collector/container/devel/final-step.sh
Non-minimal UBI images come with `gdbserver` pre-installed, so replacing it in the current dockerfile via `sed` seems like the best way to keep it up to date without having to resort to any weird workarounds.
The PR also does some cleanup, moving certain `make clean` commands and `.gitignore` lines to be closer to the place they are actually used.
=> Use regular UBI as base for dev images

ansible/group_vars/all.yml
Bumping the Garden Linux VM version used for testing to the latest (934.6).
=> Bump Garden Linux VM to version 934.6

collector/collector.cpp, collector/lib/CollectionMethod.h, collector/lib/CollectorArgs.cpp, collector/lib/CollectorArgs.h, collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/CollectorService.cpp, collector/lib/CollectorService.h, collector/lib/Diagnostics.h, collector/lib/DriverCandidates.cpp, collector/lib/DriverCandidates.h, collector/lib/GetKernelObject.cpp, collector/lib/HostConfig.h, collector/lib/HostHeuristics.cpp, collector/lib/KernelDriver.h, collector/lib/Sysdig.h, collector/lib/SysdigService.cpp, collector/lib/SysdigService.h, collector/test/DriverCandidatesTest.cpp, collector/test/HostHeuristicsTest.cpp
These changes should make it relatively easy to wire in the CO.RE eBPF probe for loading. They also put in place a fallback mechanism, allowing to try regular eBPF probes in case the CO.RE probe fails.
=> Add CO.RE eBPF candidate

collector/CMakeLists.txt, collector/collector.cpp, collector/lib/AbortHandler.cpp, collector/lib/AbortHandler.h, collector/test/AbortHandler_test.cpp
Collector already uses a signal handler to report the stacktrace in case of failures, but doesn't report all the symbols because:
* Collector is build without `-rdynamic`, missing some set of symbols in the dynamic symbols table [[1]]. Adding it means the binary will become bigger on the amount of added symbols (5.9 Mb vs 4.7 Mb without it). Worth noting that those are not debugging symbols.
* Collector is build without `-fno-omit-frame-pointer`, potentially missing some part of the stacktrace [[2]]. Adding it means a slight performance overhead, but it's well known that it's negligible. E.g. Fedora project recently switched to use it by default [[3]].
Adding those two options will give more readable stacktrace, that contains reasonable symbolic names for functions. But the C++ parts are …
=> Stacktrace improvements

collector/lib/GetKernelObject.cpp
Testing has revealed there is a situation where Sensor is up, but Central isn't, and this can result in Collectors restarting due to missing drivers. Whilst being unable to download drivers is an expected behaviour, increasing the timeouts will create a bigger window for components to start without having to restart collector each time.
=> Increases driver download retries

.github/workflows/integration-tests-vm-type.yml, ansible/ansible.cfg, ansible/benchmarks.yml, ansible/integration-tests.yml, ansible/roles/create-all-vms/tasks/main.yml, ansible/roles/run-test-target/tasks/main.yml, integration-tests/scripts/baseline/main.py
More importantly, this allows to set the collection method to include the new core_bpf driver. This collection method and now be added for PRs using the 'run-corebpf-tests' label.
Fixes #1067
=> Add the ability to run tests with variable collection methods

kernel-modules/support-packages/01-collector-to-rox-version-map.py
We are currently building support packages for driver version `1.0.0` because a regex used when mapping collector versions is matching an `-rc` tag. This makes is so the regex matches release versions only
=> Only build support packages for release versions

ansible/README.md, ansible/group_vars/all.yml, integration-tests/README.md
[COS 89 was deprecated last month](https://cloud.google.com/container-optimized-os/docs/concepts/versioning#Current) and images removed from GCP, because of this our integration tests have been failing to create a VM for that particular OS. Removing the it from our test matrix should be enough to fix the tests.
We could add one of the active versions of cos, but since we already test the `dev`, `beta` and `stable` channels for it, I believe we still have enough coverage for it.
=> Remove deprecated COS 89 from tests

kernel-modules/BLOCKLIST
The blocklist lines that are removed are mostly for backports that were pending, but the versions themselves are not supported anymore. The docker desktop line is superseded by another line that blocks all docker desktop kernels.
=> Remove blocklist lines for unsupported versions

Makefile
Otherwise it will produce an image with an empty MODULE_VERSION
~- [ ] Investigated and inspected CI test results~
~  - [ ] Added unit tests~
~  - [ ] Added integration tests~
~  - [ ] Added regression tests~
The change concerns only development target.
Local testing.
=> Add MODULE_VERSION into image-dev target

collector/lib/KernelDriver.h, collector/lib/SysdigService.cpp
connscraper needs DAC_OVERRIDE in order to read /proc correctly, so when using kernel modules we drop the capability after connscraper spawns.
=> Fix connscraper capabilities

.github/workflows/collector-slim.yml, Makefile, Makefile-constants.mk, collector/Makefile
Not specifying the OS to the --platform arguments defaults to darwin on MacOS, this is not the behavior we want, we should always attempt to use linux/amd64 by default.
=> Fix image builds on MacOS

docs/how-to-start.md
Updated an example in the docs
Tested by running `docker-compose up` using the yaml file in the docs.
=> Fix docker-compose example in docs

Makefile, collector/CMakeLists.txt, collector/falcosecurity-libs
A small set of changes that enables using podman as the build engine via the podman-docker package or by symlinking docker to podman.
The collector/falcosecurity-libs symlink is removed. It is not needed now that we use a global cmake project set at the root of the repository and was causing trouble with podman.
The '--cache-from' argument takes different types of arguments for podman and docker, since the way the builder works makes it relatively hard to actually take advantage of caching, we can directly remove them.
=> Improve compatibility with podman

kernel-modules/BLOCKLIST
Stop building drivers for the 6.3 kernel version, due to a compilation error that needs to be investigated.
=> Block drivers for 6.3 kernels

kernel-modules/build/rhel8.Dockerfile
rhel8 dockerfile shows issues with installing packages like:
Problem: package elfutils-libelf-devel-0.188-3.el8.x86_64 requires elfutils-libelf(x86-64) = 0.188-3.el8, but none of the providers can be installed
- cannot install both elfutils-libelf-0.188-3.el8.x86_64 and elfutils-libelf-0.189-1.el8.x86_64
- cannot install the best candidate for the job
Address this via adding --nobest option to pick up a package candidate.
CI run is enough.
=> Add --nobest for building on rhel8

kernel-modules/build/fc36.Dockerfile, kernel-modules/build/rhel7.Dockerfile, kernel-modules/build/rhel8.Dockerfile
The centos8 packages for elfutils-libelf and elfutils-libelf-devel are currently incompatible. It is advised to add --nobest, which was attempted but didn't seem to fix the issue. This is an alternative approach in which we remove the explicit install of the library. We depend only on the `devel` package, and thus trigger a downgrade.
The failures in this PR are due to missing modules, which should be provided by a master build, once the PR is merged...
=> Remove explicit install of elfutils-libelf in containers building probes.

ansible/group_vars/all.yml, ansible/roles/create-vm/tasks/main.yml, collector/CMakeLists.txt, collector/lib/HostHeuristics.cpp, collector/lib/HostInfo.cpp, collector/lib/HostInfo.h, kernel-modules/build/fc36.Dockerfile, kernel-modules/build/rhel7.Dockerfile, kernel-modules/build/rhel8.Dockerfile
Add steps to the host heuristics to check the presence of some features required by the core_bpf collection method.
closes #1018 
=> Preflight checks for BTF support

integration-tests/container/schedule-curls/Dockerfile, integration-tests/container/schedule-curls/Makefile, integration-tests/container/schedule-curls/schedule-curls.sh, integration-tests/suites/repeated_network_flow.go
Until we understand what makes the pipe mechanism flaky.
A new mechanism to pipe shell scripts into containers has been introduced by https://github.com/stackrox/collector/pull/1047. It basically works but seemingly made master flaky.
We plan to reenable this in https://github.com/stackrox/collector/pull/1149
=> Revert to using a dedicated image for repeated_network_flow

.github/workflows/drivers.yml, kernel-modules/BLOCKLIST, kernel-modules/build/kernel-splitter.py, kernel-modules/build/oracle.Dockerfile
Before migrating to OSCI, we used to support building OL7UEK5 kernels, we had to get rid of this due to the unavailability of the image we used for the builder in that system. Since we are now building drivers on GHA and we don't have the limitation for the image, we should be able to support it again.
=> ROX-14231: Enable building Oracle Linux 7 kernels

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/KernelDriver.h
As we've discussed on some weekly syncs, we should hard fail when the CO-RE bpf probe fails to insert in order to get more visibility on problems that might arise. A configuration option to rollback the behavior to fallback on regular eBPF is added.
Fixes #1137 
=> Add an option to hard fail when the CO-RE bpf probe fails to insert

collector/lib/CollectorConfig.cpp
Currently, the logs can be slightly confusing when switching from kernel-module to ebpf collection (post removal of kernel module collection):
```
[WARNING ...] Invalid collection-method (kernel_module), using eBPF
[INFO ...  ] User configured collection-method=kernel_module
```
This is slightly confusing and implies that kernel_module is still being used.
This PR reverses the order to make the behavior clearer.
```
[INFO ...   ] User configured collection-method=kernel_module
[WARNING ...] Invalid collection-method (kernel_module), using eBPF
```
=> Minor logging reorder for clarity of collection method behavior

collector/lib/GetKernelObject.cpp
To improve start up robustness, the time out and interval for kernel driver downloads is increased:
- interval (1 second -> 5 seconds)
- Maximum timeout (90 seconds -> 3 minutes)
- Maximum attempts (90 -> 36)
Tested locally and observed correct timeout / interval behavior.
=> Bumps download interval and timeouts

kernel-modules/build/build-kos, kernel-modules/build/prepare-src
Improvement to logging of driver build directories to have better visibility on source files, following prepare-src / compile commands. Specifically to help investigate midstream failures.
=> Improves logging in driver builds

kernel-modules/build/prepare-src
Fixes the prepare-src script when copying probe source files into the necessary locations. The current wildcard fails when collector_probe.h doesn't exist (for legacy module versions) but the new one will succeed even when there are no headers. 
Tested locally
=> Fixes copy command in prepare-src

kernel-modules/build/prepare-src
The previous fix did not behave correctly on all shells, so this replaces the command with a crafted `find` version, which handles the expected differences between module versions.
=> Convert cp command to more robust find + cp in prepare-src

RELEASED_VERSIONS
--
The changes were generated automatically.
This PR was created manually, because on 3.73 stream we still used the (broken) OSCI automation to create the PR.
=> Automatic update of RELEASED_VERSIONS file for Rox release 3.73.5

collector/collector.cpp
Simply rewords the GPL notice slightly to reflect the removal of kernel modules
=> Removes kernel-module reference from GPL notice

collector/lib/CollectionMethod.cpp, collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/DriverCandidates.cpp, collector/lib/GetKernelObject.cpp, collector/lib/HostHeuristics.cpp, collector/lib/SysdigService.cpp, collector/test/DriverCandidatesTest.cpp
This avoids name conflicts by scoping the collector-method identifiers, and eases the conversion to strings.
fixes: #1157
=> Use a scoped enumeration for CollectionMethod

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/SysdigService.cpp
ROX_COLLECTOR_SET_IMPORT_USERS defaults to false, and is used to configure sinsp and its user-mgmt subsystem.
This is intended as a safeguard in case we would need to reenable it; and was deactivated to circumvent a memory management issue (CRI not available => containers never freed in user.cpp)
=> New environment variable for control set_import_users()

kernel-modules/BLOCKLIST
6.3 was already blocked, but the same build issue exists with 6.4; so extending the block rule until we pull the fixes from upstream.
CI has:
```
Blocked kernel: 6.4.0-0-amd64 2.5.0 mod
Blocked kernel: 6.4.0-0-amd64 2.5.0 bpf
Blocked kernel: 6.4.0-0-cloud-amd64 2.5.0 mod
Blocked kernel: 6.4.0-0-cloud-amd64 2.5.0 bpf
```
=> ROX-16705: Block the build of all drivers against 6.4

ansible/group_vars/all.yml
The image has been dropped from the GCP project, so this simply drops it from out test matrix.
=> Drops Ubuntu-1804-lts from test matrix

integration-tests/suites/config/config.go
Correctly sets the default REMOTE_HOST_TYPE. Without this change, the tests will segfault if a REMOTE_HOST_TYPE is not provided.
=> Fixes local default in integration test config

collector/lib/CollectorArgs.cpp, collector/lib/CollectorService.cpp, collector/lib/DuplexGRPC.h, collector/lib/NetworkConnectionInfoServiceComm.cpp, collector/lib/ProcessSignalHandler.cpp, collector/lib/ProcessSignalHandler.h, collector/lib/SignalServiceClient.cpp, collector/lib/SignalServiceClient.h, collector/lib/SysdigService.cpp, collector/lib/SysdigService.h, docs/how-to-start.md
First step towards standalone Collector for development. Replace SignalServiceClient for ProcessSignalHandler with an interface and allow passing a dummy implementation to dump everything into stdout. Having this in place, one can remove --grpc-server argument when building an image, and Collector will not try to connect anywhere.
The result looks like this:
```
[DEBUG   2023/06/16 14:05:47] (ProcessSignalFormatter.cpp:168) Process (104759): ls --coreutils-prog-shebang=ls /usr/bin/ls
[DEBUG   2023/06/16 14:05:47] (SignalServiceClient.cpp:116) GRPC: {"signal":{"processSignal":{"id":"e43115e4-0c4e-11ee-9beb-0242ac120003","containerId":"8d809b26986d","time":"2023-06-16T16:05:49.482254981Z","name":"ls","args":"--coreutils-prog-shebang=ls …
```
=> Allow to run Collector without grpc connection

builder/Dockerfile, collector/CMakeLists.txt
Mixing the 'curl' custom_target with the 'curl' library dependency was making cmake rather angry (segfault)
We fix the curl dependency issue, and then can make use of the default cmake version.
=> Use the default cmake version

ansible/group_vars/all.yml
Integration tests on the Fedora platform are failing due to known issues, we will block them for the time being and reenable them once the issues are resolved.
=> Block failing Fedora integration tests

collector/lib/CollectorConfig.cpp, integration-tests/suites/common/collector_manager.go
Change the default collector configuration so that it falls back to eBPF when the CO-RE BPF driver fails to be inserted.
Fixes #1224
CI should be enough since the change is pretty straightforward.
=> Allow collector to fallback to regular eBPF by default

.clangd
This file is used by clangd to find the location where the compile_commands.json file is normally located. We don't create this file by default, though generating it is trivial, so when running a dev container for continuous compilation of the collector binary it is useful to have.
This was originally meant to be added in #948, which has been stuck for quite some time and I don't currently have time to pick back up, but I'd still want to have this file added so I can stop carrying the change in my local environment.
This is a development change only and shouldn't affect anything other than those environments using `clangd` as a language server.
=> Add .clangd file

.github/workflows/add-new-pr-to-oss-triaging.yml
These lint errors have existed for sometime, but have remained only because the file hasn't been modified since creation. Following some testing of actionlint when reviewing #1246 I thought I'd tackle these now.
This is only a cosmetic change.
=> Fixes lint errors in add-new-pr-to-oss-triaging workflow

.github/workflows/lint.yml, .pre-commit-config.yaml
The actionlint-docker commit hook has some issues when running using podman from macos, it tries to mount the repository in a way that is not supported and fails. Because fixing this upstream would be annoying and installing actionlint locally shouldn't be a big deal, we should start using the native binary option. This is also preferable to committing with --no-verify and relaying on people running the check manually.
For instructions on how to install actionlint see: https://github.com/rhysd/actionlint/blob/main/docs/install.md
This is a change that only affects developer workflow.
=> Use non-docker actionlint commit hook

collector/lib/GetKernelObject.cpp, collector/test/GetKernelObjectTest.cpp, utilities/driver-checksum.sh
Have collector print the sha256 checksum for the driver it uses. Same as #1237, this is part of the groundwork for unifying the upstream and downstream built drivers. By printing the checksum for a driver being used it'll be easier for us to check where the driver comes from in case a user reports an issue.
A small script for downloading drivers from GCP and validating checksums is also provided, in hopes that if we ever need to validate the source of a driver it will make the work somewhat easier.
=> Print checksum of drivers being used

.github/workflows/collector-full.yml, .github/workflows/cpaas.yml, .github/workflows/integration-tests-vm-type.yml, .github/workflows/integration-tests.yml, .github/workflows/main.yml
This is step one into trying to make the downstream built drivers authoritative. The nightly runs will start building true full images with all drivers, but the downstream built drivers will take precedence over all others.
There were some issues running both the cpaas and upstream integration tests for the PR in parallel due to VM names colliding, so a final section has been added to the job-id to prevent this.
=> Use real full images on the downstream nightly

.github/workflows/main.yml
In order to ease the PR experience a little, this change will make the workflow re-run when labels are changed (added or removed.)
=> Makes main workflow run on PR label changes

.github/workflows/cpaas.yml, .github/workflows/gardenlinux-bumper.yml, .github/workflows/integration-tests.yml, .github/workflows/support-packages.yml
Final (?) shift of notifications over to oncall channel. team-acs-collector-notifications now reserved for github notifications and the one notification about MODULE_VERSION (i.e. notifications that are not the responsibility of the signal handler)
=> Moves most notifications to oncall channel

integration-tests/images.yml, integration-tests/suites/base.go, integration-tests/suites/connections-and-endpoints.go, integration-tests/suites/process_network.go, integration-tests/suites/repeated_network_flow.go
Currently the mock grpc server only reports the latest connection that it sees for each container. We should have tests were multiple connections are seen per container. We should also make sure that when we expect to see one connection reported for a container, that there is only one connection for that container and not multiple connections. This PR updates the mock grpc server image to one that reports multiple connections per container and makes changes to the integration tests so that they get an array of connections rather than just a string representing one connection. Currently asserting that we see the expected number of connection and that all of the connections are ones that we expect to see causes many of the tests to become flaky or fail. For now we just do logging when the …
=> Jv mock grpc server should report multiple connections

.github/workflows/collector-slim.yml, .github/workflows/init.yml, ansible/ci-build-collector.yml
After #1264 got merged, a weird behavior showed up on the master branch, the `cache` tag for the builder images that is meant to be the multiarch manifest for the latest builder image was being linked to the amd64 image only. Investigation showed that tagging and pushing via ansible is updating the `RepoTags` field to contain both the base image and the arch specific image.
RepoTags before #1264:
```
podman inspect --type image --format='{{ .RepoTags }}' quay.io/stackrox-io/collector-builder:cache-amd64
[quay.io/stackrox-io/collector-builder:cache-amd64]
```
RepoTags after #1264:
```
podman inspect --type image --format='{{ .RepoTags }}' quay.io/stackrox-io/collector-builder:cache-amd64
[quay.io/stackrox-io/collector-builder:cache quay.io/stackrox-io/collector-builder:cache-amd64]
``` …
=> Prevent cache builders for specific archs from overwriting the multiarch manifest

.github/actions/create-multiarch-manifest/action.yml, .github/workflows/collector-slim.yml
This PR started as a way to disable the s390x builds after an error broke CI on our master branch but, after fixing that issue, it turned into a way to easily disable and enable individual architectures to the collector-slim workflow. Changing the archs we build for has always been easy, simply add or remove them from the build matrix, the manifest creation on the other hand has a bunch of arch dependent images hardcoded and requires multiple changes to it. To make editing the archs supported in the manifest creation as simple as the image build step, a new action is created and archs supported can be supplied via a space separated environment variable.
=> Move multiarch manifest creation to a separate action

.github/actions/support-package-driver-matrix/action.yml, .github/workflows/main.yml, kernel-modules/support-packages/04-create-support-packages.sh, kernel-modules/support-packages/utils.sh
With the recent changes introduced by #1248, a few potential failures can occur when the downstream drivers have not yet been mirrored upstream. Checking before using them should fix the issue.
=> Check bucket has drivers before using it

.github/workflows/collector-slim.yml
#1264 introduced a bug where PRs are pushing the `cache` tag for builders, this change should restore the previous behavior.
=> Push the builder image only when absolutely necessary

kernel-modules/BLOCKLIST
Latest version of collector is able to build drivers for 6.3+ kernels, but legacy versions still fail. We block them for now and we can backport the fix if needed in the future.
=> Block 6.3+ kernels on failing versions

.github/workflows/collector-slim.yml
GHA has a timeout property for jobs and steps, if the timeout of a step is longer than that of a job, then it is still killed. This PR moves the timeout extension for slim images from the build step to the job as to prevent this early killing.
=> Properly extend multiarch build timeout

.github/workflows/collector-slim.yml
Turns out that, after trying to extend just the step in #1270 and then trying to just extend the timeout in #1276 (which I should've guessed was not gonna be enough), the correct way is to extend both timeouts, otherwise GHA just stops after 6 hours.
CI should be enough (but reality is, this change is tested on master when the build takes longer than 6 hours).
=> Extend the build image step to match the job timeout

.github/workflows/collector-full.yml, .github/workflows/cpaas.yml, .github/workflows/main.yml
Instead of using an image built upstream with the downstream drivers, the CPaaS workflow will start running tests using a slim image built downstream with the latest commit for collector. In order to continue testing the downstream built drivers, a full image is built by embedding the downstream built drivers in the slim image and running the tests in offline mode.
=> Use the downstream built image for testing

.github/workflows/collector-builder.yml, .github/workflows/collector-slim.yml, .github/workflows/main.yml, ansible/README.md, ansible/ci-build-builder.yml, ansible/ci-build-collector.yml, builder/Dockerfile
Skip the builder image build when no changes would make modifications to the actual image (i.e.: no change to third_party libraries and the builder directory itself).
=> Skip builder image build when it is unmodified

.github/workflows/cpaas.yml, .github/workflows/main.yml
The only purpose for this change is to bring additional clarity to our CI pipeline, since the main workflow was becoming too crowded.
Summary for a PR before this change:
After this change the summary gets split in two:
This makes them a bit easier to understand and follow what is going on.
=> Split cpaas workflow from main

.github/workflows/collector-builder.yml
The docs for the dorny/paths-filter action are somewhat confusing, apparently not checking out the repo works fine on PRs, but fail miserably on any other sort of trigger:
https://github.com/dorny/paths-filter/issues/60
Looking closer at the docs, seems a simple checkout should work for the cases we care about.
=> Checkout code when determining if builder should be built

.github/workflows/collector-slim.yml
We used to pull the builder image in the `skip-multiarch-builds`, which now breaks when the builder's build is skipped (builder tag not set).
This seems uneeded now, so let's just remove it.
=> Remove stale pull of builder image with skip-multiarch

collector/CMakeLists.txt, collector/lib/CollectorConfig.h, collector/lib/NetworkSignalHandler.cpp, collector/lib/SysdigService.cpp, integration-tests/integration_test.go
The Collector should report connections that can actually be used to transfer information.
In the case of a TCP connection in asynchronous mode, we have to postpone declaring the connection and
wait until we know the state of the socket.
- When connect returns `INPROGRESS`, we do not declare a connection anymore.
- If the socket is pending and a getsockopt(SO_ERROR) returns a success, we declare this connection
=> ROX-18736 Report connections only when they are established

collector/lib/HostHeuristics.cpp
Even if using ebpf collection method, test for core_bpf to help with adoption. Here is how it looks like:
```
[INFO    2023/08/16 12:02:27] (HostHeuristics.cpp:53) CORE_BPF collection method is available.
HINT: Check the documentation to compare features of available collection methods.
```
Local testing.
=> [ROX-18733	] Always verify core_bpf

.github/workflows/init.yml
The subdirectory being checked for downstream drivers is wrong, it should check the `x86_64` subdirectory.
=> Check the correct subdirectory for downstream drivers

.github/workflows/cpaas-sync-drivers.yml, .github/workflows/cpaas.yml, .github/workflows/init.yml, .github/workflows/main.yml, .github/workflows/upload-drivers.yml
Unify all downstream and upstream drivers for all archs in a single bucket so they can be downloaded by collector when running online.
=> Merge downstream and upstream drivers for online download

.github/workflows/collector-slim.yml, ansible/ansible.cfg, ansible/ci-build-collector.yml, ansible/roles/run-test-target/tasks/test-collection-method.yml
To reduce the amount of useless information in the ansible output (setup tasks, skipped tasks etc) this PR enables the `selective` stdout callback which will only print tasks that are explicitly opt-in via the `print_action` task, with the exception of failures which are always printed
As a first pass, this PR also opts-in with integration testing tasks and build tasks, but none of the VM creation or provisioning task. This is by no means set in stone and if more tasks make sense for logging then we can opt-in.
The advantage should be that the CI logs are more readable and we can identify flakes/failures more easily. 
Tested locally. Example output, including some successes and failures:
```
ansible-playbook \
-i dev …
```
=> Improve ansible output

.github/workflows/collector-full.yml, .github/workflows/main.yml, ansible/README.md, ansible/ci-build-collector-full.yml
Use the downstream built drivers for P and Z alongside the downstream built images to build full collectors images.
=> Build multiarch full collector images

.github/workflows/integration-tests.yml, ansible/roles/run-test-target/tasks/build-tests.yml, ansible/roles/run-test-target/vars/main.yml
With the tests now running directly on the host, some hosts mount `/tmp` `noexec` which means we get permission denied errors when trying to run the integration tests from that location. This PR changes the location to the user's home directory to avoid the `noexec` constraint. 
Longer term, tests should be containerized to avoid this issue altogether
Tested locally against garden linux, will rely on CI to test the remainder of the platforms.
=> Fixes integration tests on noexec mounted directories

collector/lib/FileDownloader.cpp, collector/lib/FileDownloader.h, collector/lib/GetKernelObject.cpp, collector/test/FileDownloaderTest.cpp
Loosely related to ROX-19614, when sensor and collector are deployed to a namespace other than stackrox, the URL logged by collector points to it trying to download the driver from sensor.stackrox.svc when it should be using sensor.<namespace>.svc.
This change adds a GetEffectiveURL method to the FileDownloader class, so we can now print the correct URL the driver will be downloaded from.
Deployed the image to a non standard namespace and checked the collector logs:
```
[INFO    2023/09/12 10:38:20] Sensor configured at address: sensor.rhacs-operator.svc:443
[INFO    2023/09/12 10:38:20] Attempting to connect to Sensor
[INFO    2023/09/12 10:38:20] Successfully connected to Sensor.
[INFO    2023/09/12 10:38:20] Module version: 2.6.0
[INFO    2023/09/12 10:38:20] …
```
=> Use the effective URL for logging when downloading a driver

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/CollectorService.cpp, collector/lib/ConnTracker.cpp, collector/lib/ConnTracker.h, collector/test/ConnTrackerTest.cpp
A new feature-flag ROX_ENABLE_EXTERNAL_IPS environment variable controls whether external network connections which do not match any defined known network are aggregated in the default bucket.
The default value is false, which corresponds to the previous behavior. 
=> ROX-19605: new feature-flag to control aggregation of unmatched IPs

kernel-modules/BLOCKLIST
RHEL8.9 received backports which breaks the probe's kernel-version-adaptation-macros for most versions.
This PR blocks modules from RHEL8.9 and onwards.
=> ROX-19721: block modules for RHEL >= 8.9

ansible/ci-build-collector.yml
Rely on ansible to report stderr rather than dumping the build log in several parts. Avoids confusion and ensures a clean output on success.
Tested with and without a compilation errors, and logs shared with @Molter73 for comment
=> Include stderr in build output ansible

collector/lib/FileDownloader.cpp, collector/lib/FileDownloader.h
Curl's URL API was added on version 7.62, but RHEL 8 only support 7.61. We could've added libcurl to the builder as a dependency, but given we are still trying to sort builder versioning, the image already takes a pretty long time to build and we only really require a very small subset of the URL API, I opted for adding a small subclass to FileDownloader that will handle parsing of URLs for our use case. The URL API also returned C strings that were copies of what was stored internally and needed to be copied into proper std::strings and free'd, so this approach is a bit cleaner IMO and requires less memory manipulation.
The unit tests added by #1326 should provide coverage for our use case.
=> Remove dependency on curl's URL API

utilities/troubleshooting/missing-probe.sh
The script modified here does a few checks when a probe is missing. It was checking for bundles in a bucket that is no longer used. The bucket is updated here. This script also checks for both ebpf and kernel module probes by default. I am keeping the checks for kernel modules for now, but the default is switched to ebpf.
~~ - [ ] Added unit tests~~
~~ - [ ] Added integration tests~~
~~ - [ ] Added regression tests~~
This isn't a change to the product itself.
Test for missing probe
```
./missing-probe.sh 5.14.0-284.30.1.el9_2.x86_64 2.6.0
################
Checking if kernel version is supported by branch master
Kernel 5.14.0-284.30.1.el9_2.x86_64 NOT found in kernel-modules/KERNEL_VERSIONS in the master branch …
```
=> Jv fix missing probe troubelshooting

.github/workflows/collector-full.yml
This change is missing after the merge of #1271
=> Fix retag-collector-full workflow

ansible/roles/run-test-target/tasks/main.yml, ansible/roles/run-test-target/tasks/pull-images.yml
This PR will pre-pull test images on CI to make test execution times more consistent. There is currently a situation where test setup might start various containers and then wait to pull an image. When the timing of events is important/crucial, this waiting can cause flakes.
This behaviour is disabled when running individual test suites because the upfront performance penalty is significant at that level. I have yet to figure out a neat way of only pulling the images that the requested test uses, but that can be looked at in a follow up if it is deemed useful. 
Tested locally, with timings:
```
➜  collector git:(giles/ROX-14542-pre-pull-all-images) ✗ time make -C ansible/ integration-tests COLLECTION_METHODS=core-bpf …
```
=> Pull all test images to avoid timing issues during tests

integration-tests/suites/mock_sensor/expect_conn.go, integration-tests/suites/mock_sensor/expect_proc.go
Improves the logging output for clarity in scenarios where number of events received exceeds the expected number.
Before:
`only retrieved 4 processes, expected 3` 
After
`found 4 processes (expected 3)`
=> Makes expect logging clearer when more events are reveived than expected

integration-tests/suites/async_connections.go, integration-tests/suites/base.go, integration-tests/suites/benchmark.go, integration-tests/suites/collector_startup.go, integration-tests/suites/connections_and_endpoints.go, integration-tests/suites/duplicate_endpoints.go, integration-tests/suites/image_json.go, integration-tests/suites/listening_ports.go, integration-tests/suites/missing_proc_scrape.go, integration-tests/suites/process_network.go, integration-tests/suites/procfs_scraper.go, integration-tests/suites/repeated_network_flow.go, integration-tests/suites/socat.go, integration-tests/suites/symlink_process.go
Testify does not currently support guaranteed execution of `TearDownSuite` (see issue https://github.com/stretchr/testify/issues/1123) This PR provides a function that wraps common and critical teardown code that has historically affected our tests considerably. 
In particular:
- stopping collector
- cleaning up test containers
- stopping the stats container
This will mean that even if a test setup fails, subsequent tests should have the same "clean slate," and won't fail.
Tested locally, using normal test execution and with a forced panic
=> ROX-19899: Implement SuiteSetup recovery to encapsulate critical cleanup

integration-tests/suites/async_connections.go, integration-tests/suites/base.go, integration-tests/suites/benchmark.go, integration-tests/suites/collector_startup.go, integration-tests/suites/common/collector_manager.go, integration-tests/suites/connections_and_endpoints.go, integration-tests/suites/duplicate_endpoints.go, integration-tests/suites/image_json.go, integration-tests/suites/listening_ports.go, integration-tests/suites/missing_proc_scrape.go, integration-tests/suites/process_network.go, integration-tests/suites/procfs_scraper.go, integration-tests/suites/repeated_network_flow.go, integration-tests/suites/socat.go, integration-tests/suites/symlink_process.go
To avoid having to provide (1) a hard-coded json string and (2) duplicated default options across all tests, this PR introduces `CollectorStartupOptions` structure which allows tests to set specific options/environment variables/mount points before starting collector. The collector manager itself is responsible for serializing this information as necessary and tests only need to modify the options that they need to.
Options provided by a test _always_ supersede those defined by default in the collector manager.
Tested and built locally against Garden Linux (of all things) CI will catch everything else. This should have no impact on the outcome of the tests.
=> ROX-19898: refactor collector configuration in tests

integration-tests/scripts/baseline/main.py, integration-tests/suites/async_connections.go, integration-tests/suites/base.go, integration-tests/suites/benchmark.go, integration-tests/suites/connections_and_endpoints.go, integration-tests/suites/duplicate_endpoints.go, integration-tests/suites/image_json.go, integration-tests/suites/listening_ports.go, integration-tests/suites/missing_proc_scrape.go, integration-tests/suites/process_network.go, integration-tests/suites/procfs_scraper.go, integration-tests/suites/repeated_network_flow.go, integration-tests/suites/socat.go, integration-tests/suites/symlink_process.go
Removes some boilerplate from the tests around the printing and storage of various perf results after the tests have executed. Now, perf results are all handled within the integration tests base struct, and the test simply has to call `WritePerfResults` in `TearDownSuite`
This also fixes an issue where container stats weren't initialized properly, resulting in invalid perf reporting. 
Tested locally against RHEL 8 and RHEL 9
=> Clean up of perf results accesses and storage

.github/workflows/collector-builder.yml
Multiarch builders take a really long time to build, so on PRs we should allow the `skip-multiarch-builds` label to skip them the same way we do for collector slim and full.
=> Allow skipping multiarch builder on PRs

ansible/group_vars/all.yml, ansible/roles/create-vm/tasks/create-s390x-vm.yml, ansible/roles/create-vm/vars/s390x.yml
Just some tidy up and minor refactoring of ansible vars files. CI should be sufficient for testing.
=> Impove group_vars docs and move s390x vars to create-vm role

.github/workflows/collector-builder.yml, .gitmodules, Makefile, Makefile-constants.mk, builder/.dockerignore, builder/Dockerfile, builder/install/50-luajit.sh, builder/install/install-dependencies.sh, docs/how-to-start.md, utilities/sinsp-builder.sh
Versioning for the builder has been changed so that tags and release branches build their own versions without conflicting with master and PRs. The builder has also undergone a slight refactor so instead of using the entire repository as its context, just the builder directory is used.
We also removed luajit from the list of dependencies, this hasn't been needed since the removal of chisels on #1290.
Supersedes #1315.
=> Implement builder versioning

.github/workflows/collector-builder.yml, .github/workflows/collector-full.yml, .github/workflows/collector-slim.yml
Multiarch builds take a pretty long time which slows down dev work. Making them opt-in for PRs should make dev a lot faster even if we might get broken builds on master every now and then.
All tests should force the builder image to be built.
=> Skip multiarch builds as a default

.github/workflows/collector-full.yml
CPaaS full image builds were being skipped because the trigger for them is `schedule`, but the check only accounted for `push` triggers. Changing this condition to not be a PR should work for both conditions.
Testing on schedule events is complicated, since the change is small I propose getting it merged and let the real event trigger.
=> Fix CPaaS full images build

.github/workflows/cpaas.yml, ansible/group_vars/all.yml
Enables s390x testing in CPaaS workflow.
There is an ongoing workflow to add it to PRs as well as on the CPaaS schedule, but this will give us some idea of what's affecting s390x more frequently than currently.
CI is sufficient
=> Enable s390x always in CPaaS workflows

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/CollectorService.cpp, collector/lib/CollectorStats.h, collector/lib/CollectorStatsExporter.cpp, collector/lib/CollectorStatsExporter.h, collector/lib/ConnTracker.cpp, collector/lib/ConnTracker.h, collector/lib/NetworkStatusNotifier.cpp, collector/lib/NetworkStatusNotifier.h, collector/test/ConnTrackerTest.cpp, collector/test/NetworkStatusNotifierTest.cpp, docs/references.md, docs/troubleshooting.md
We add a set of new Prometheus metrics reporting the total amount of connections known by collector and their creation rate over a reporting-period (scrape-interval).
These metrics are split per connection direction (inbound, outbound) and the location of the peer address (private or remote IP).
Excerpt on an idle single-node k8s:
```
rox_connections_total_count{dir="out",peer="public"} 36
rox_connections_total_sum{dir="out",peer="public"} 18
rox_connections_total{dir="out",peer="public",quantile="0.5"} 0
rox_connections_total{dir="out",peer="public",quantile="0.9"} 1
rox_connections_total{dir="out",peer="public",quantile="0.95"} 3
rox_connections_total_count{dir="out",peer="private"} 36
rox_connections_total_sum{dir="out",peer="private"} 59537 …
```
=> ROX-19778: Load metrics for connections

collector/lib/HostHeuristics.cpp
When running on Power machines, we are wrongly printing a message stating that CORE_BPF is available on the platform, but we don't support it in code, so we shouldn't be printing the message. Additionally, setting CORE_BPF as the collection method should hard fail since it is unsupported.
Will try to test this on a power VM, but the change is small enough that should be good enough to be merged as is IMO.
=> Remove CORE_BPF available message on Power machines

ansible/ci/group_vars/all.yml, ansible/dev/group_vars/all.yml, ansible/roles/create-vm/tasks/create-s390x-vm.yml, ansible/roles/create-vm/vars/s390x.yml
IBM cloud VMs are created with 10GB disks by default, this is enough for our tests but it's also a heavy limitation when trying to use one of these VMs for dev work. This patch bumps the size of the created disk to 20GB, which is not huge, but enough for creating a few images and running some tests.
=> Bump disk size for s390x VM when running in dev mode

collector/lib/FileDownloader.cpp, collector/lib/Logging.cpp, collector/lib/Logging.h, collector/lib/SysdigService.cpp
This change unifies log severity between our code and Falco and makes it so their log messages are logged with our logging mechanism, giving a more unified look for the logs and improving debugability with additional information for all events being processed. Originally, the container engine mechanism was very noisy on debug level, but since we stopped using the default engine this noise has been reduced significantly.
Run some tests manually and checked the output on info and debug levels.
<details>
<summary>Example log from one of the tests</summary>
```
Collector Version: 3.17.x-10-g2935f965cf
OS: Red Hat Enterprise Linux 9.2 (Plow)
Kernel Version: 5.14.0-284.30.1.el9_2.x86_64
Starting StackRox Collector...
[INFO    2023/10/27 09:47:29] Hostname: …
```
=> Use a logging callback for Falco log messages

kernel-modules/BLOCKLIST
A patch was introduced to solve build issues on earlier RC versions of 6.6, which is now causing
build issues. It has been mostly reverted upstream.
Block temporarily those kernels while we work on pulling upstream.
This does not touch the Collector code, we just want to make the drivers build happy.
=> ROX-20541: Temporarily exclude kernels 6.6 from build

integration-tests/container/Makefile, integration-tests/container/README.md
The integration tests depend on several images. Each of these images have their own directory in integration-tests/container. Each of those directories has a Makefile that can be used to build and push the images. CI builds and pushes these images using the Makefiles. To make this more convenient when running the integration tests locally a Makefile is added to the integration-tests/container to build and push all of the images, so that the Makefile targets don't have to be run individually for each directory.
All of the Makefiles are very similar except for perf. Seems like this is a violation of DRY and they should be consolidated into the Makefile added in this PR.
~~ - [ ] Added unit tests ~~
~~ - [ ] Added integration tests ~~
~~ - [ ] Added regression tests ~~ …
=> Jv build all integration test containers

kernel-modules/dev/build-drivers.sh
From a clean state, the driver config is not copied into the source tree like it is for CI builds. This PR simply copied the file over. 
Tested locally. Should not affect CI.
=> Fixes dev driver builds by copying driver config

.github/workflows/drivers.yml, .github/workflows/main.yml
Exclude drivers and support package builds from release branches and tags, these artifacts are built by every commit on the master branch. The only complication that might arise from this is doing a patch release for our drivers, since the tags and release branches will not have drivers available until master does a CI run. There are a few workarounds for this, like adding a filter checking to see if the `MODULE_VERSION` was changed, I'll experiment a bit before opening the PR for review.
=> Build drivers and support packages on master and PRs only

.github/workflows/cpaas.yml, integration-tests/Dockerfile
Since the integration tests have been containerized, the CPaaS workflow needs to build the image in order for it to be able to run the tests.
=> Build test container on CPaaS workflow

.github/workflows/cpaas.yml
#1359 added a concurrency group to the cpaas workflow. Unfortunately, since it's the same as the one in the main workflow, they are colliding when running from PRs. This small change should stop the collision.
Ensure both the main and cpaas steps run when using the `run-cpaas-steps` label.
=> Use a concurrency group different from the one on main

ansible/ci-build-tests.yml, ansible/group_vars/platform_fcarm.yml
The integration test container is not being build for ARM64 and it's causing failures on the main branch, this should fix it.
=> Add ARM64 to the platforms used for the integration test container

ansible/group_vars/all.yml
After unsuccessfully trying to get upstream Garden Linux to help us crawl newer kernels, we've decided to stop maintaining eBPF probes for the distro in favour of the CO-RE BPF driver.
=> Block Garden Linux eBPF tests

kernel-modules/BLOCKLIST
These drivers are broken and require a patch, see: https://github.com/falcosecurity/libs/pull/1174
However, kernel modules are deprecated and maintained as best effort only, so for the moment we will just block the affected kernels.
=> Block RHEL 9.3 kernel modules

.github/workflows/integration-test-containers.yml
When skipping the integration tests on a PR, we can safely skip building the integration-test container. This container always builds as multiarch and can take quite a bit to finish.
=> Skip integration-test container build

ansible/dev/group_vars/all.yml, ansible/dev/inventory_gcp.yml
Now that the stackrox-dev project is being deleted, we need to shift the development inventory to the new project. There may be a follow up in the coming weeks to do the same for stackrox-ci
Tested locally. This PR does not affect anything beyond local testing.
=> Switches ansible dev inventory to acs-team-sandbox

.github/workflows/cpaas.yml, .github/workflows/init.yml, .github/workflows/main.yml
There's a bug when building full multiarch images on PRs. The bucket used for pulling drivers is changed in the main CI workflow to use a staging bucket, but the main CI never pushes drivers for P/Z to this bucket, so it fails because it find no drivers to add into the image. Changing to the staging bucket should only be done by the CPaaS workflow, so an additional condition for this is added.
=> Fix multiarch full image builds on PRs

.github/workflows/collector-builder.yml, .github/workflows/main.yml
Ensure `collector-builder-tag` is set when a rebuild is not needed.
=> Ensure collector-builder-tag is set when a rebuild is not needed

kernel-modules/BLOCKLIST
RHEL 8.9 with latest kernels contains backports for the once fixed issue for kernel modules [[1]]. Kernel modules are going to be deprecated soon anyway, so simply block their build for those versions with module version 2.3.0 & 2.4.0 (the last yet in build). 
[1]: https://github.com/falcosecurity/libs/issues/918
=> Avoid kernel modules for rhel 8.9

.github/workflows/integration-test-containers.yml, ansible/ci-build-tests.yml
This should speed up the "normal" PR builds substantially.
=> Test container builds now respect run-multiarch-build label

collector/CMakeLists.txt
Customize Falco to log ASSERTS if configured.
Local testing, the result looks like this:
```
[ERROR   2023/11/01 14:13:55] (Logging.cpp:105) ASSERTION !(evt->m_fdinfo->is_unix_socket() || evt->m_fdinfo->is_ipv4_socket()) at /tmp/collector/falcosecurity-libs/userspace/libsinsp/parsers.cpp:3092
```
=> Log asserts

.github/workflows/collector-builder.yml, .github/workflows/collector-full.yml, .github/workflows/collector-slim.yml, .github/workflows/integration-test-containers.yml, .github/workflows/integration-tests-vm-type.yml
With the move to the selective callback in ansible, we sometimes lose some valuable information about certain error conditions. This PR will switch the callback to `debug` when we re-run the workflow with debug logging in GHA.
=> Enable debug stdout callback in ansible when GHA is in debug mode

docs/troubleshooting.md
Mention how to use gperftools in troubleshooting section.
=> Add gperftools docs

.github/workflows/integration-test-containers.yml
Currently, images for integration tests on s390x are build only if requested via label or pushed. It turns out the scheduled CPaaS related workflow does neither of those, meaning it fails on integration tests. Extend current logic to build images when the github event is 'schedule'.
=> Build multiarch test images on schedule

collector/container/Dockerfile, collector/container/status-check.sh, integration-tests/suites/base.go, integration-tests/suites/benchmark.go, integration-tests/suites/image_json.go, integration-tests/suites/mock_sensor/expect_proc.go, integration-tests/suites/perf_event_open.go
In the past we've got situations when the CI integration tests reports were not extensive enough to clarify what's going on, and we were launching a full-blown debugging process just to find out that the probes were missing.
To make initialization issues more visible, make integration tests verbose about them:
* Introduce a HEALTHCHECK for the Collector docker image, based on the /ready Civet API. This command would be ignored on K8S, but we could use it on CI for containers filtering.
* Wait for Collector container to become healthy first before proceeding with the rest of tests. This will make it immediately clear if the test is failing due to missing probes.
* Make self-checks verification a hard failure. Currently, we wait for the self-checks, but do not report if they're missing. …
=> Make tests verbose about startup failures

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/KernelDriver.h, docs/references.md
Make sinsp event buffer related parameters (how many buffers to allocate and of what size) configurable via Collector config. The default values are the same as before, but it makes memory utilization more flexible. Taking into account the difference between on-demand allocation for ebpf and right-away allocation for core_bpf, this can help to address situations, when users are unhappy about Collector memory consumption, e.g. one can lower it down significantly by reducing number of buffers or their size -- the trade-off being of course higher latencies due to congestion on buffers.
Local testing.
=> Configurable sinsp buffer

collector/lib/CollectorConfig.cpp
This makes it so that the afterglow period cannot be set to a value greater than five minutes. If the user tries to set the afterglow period to a value greater than five minutes, it is set to five minutes. The user is also warned of this fact.
There is a bug resulting from the fact that afterglow delays the reporting of closed connections, such that the associated service/deployment/pod may have been deleted. To fix this sensor must store information about entities for longer than the afterglow period. However, sensor does not know how long the afterglow period is. The temporary solution is for sensor to assume that the afterglow period is five minutes and to limit the afterglow period in collector to five minutes.
See below for the PR to have sensor remember entities after they are …
=> Jv rox 21454 limit the afterglow period to 5 minutes

integration-tests/suites/base.go, integration-tests/suites/mock_sensor/expect_proc.go
Currently, we use health check to verify Collector has started properly, but not all the pipelines have the health check enabled in the image. It's fine, because we want to use it only for testing, so make the integration tests smarter to handle situations where there is no health check in the image.
Local testing. CI is sufficient.
=> Skip health check for CPaaS workflow

ansible/group_vars/all.yml
The garden linux VMs are created by image, so the image name is necessary to block the testing.
=> Fixes garden-linux eBPF block

ansible/roles/run-test-target/tasks/main.yml, ansible/roles/run-test-target/tasks/pull-images.yml
This PR makes it so that errors when pre-pulling images are ignored. This is to prevent some flakes on certain platforms (currently RHCOS is experiencing issues.) When pre-pulling fails, the tests will still attempt to pull missing images, so tests should be largely unaffected.
Tested locally.
=> Make test image pre-pulling more robust

.github/workflows/collector-builder.yml, .github/workflows/collector-slim.yml
Fixes a slight bug in the if statements for builder and slim image builds, which were running the s390x builds twice (once in qemu, once natively) but only on master.
Can only rely on CI for this
=> Fixes duplicate s390x builds on master

kernel-modules/build/prepare-src
Some code moved around in prepare-src which meant that the source archive is sometimes created from the wrong directory. This simply fixes that.
=> Ensure driver archive is created in the right directory

collector/container/rhtap-slim.Dockerfile
After switching to vanilla Falco libsinsp is build statically. Do not copy the shared libsinsp into the final image.
=> [rhtap] Remove libsinsp

collector/container/rhel/install.sh
https://redhat-internal.slack.com/archives/CFMQ5C2TT/p1705417422117649
This was changed in #1407 in the assumption that `-y` is superfluous (https://github.com/stackrox/collector/pull/1407#discussion_r1416205667), which is true only for UBI8 images.
For more details, ref the [Confluence page](https://stack-rox.atlassian.net/wiki/spaces/StackRox/pages/855998488/Proposal+Explicitly+List+Testing+Steps+on+PRs) …
=> fix: dependency installation in collector-slim upstream build requires explicit -y

builder/Dockerfile
clang-15 is no more available in centos:stream9
Falco claims to be fine with anything above 12.
=> Use clang-17 instead of clang-15

integration-tests/suites/base.go
It seems that waiting for Collector to become healthy for 1 minute is not stable enough, so bump the timeout.
=> Bump health check timeout

RELEASED_VERSIONS
These two versions were not marked as published due to a bug in the upstream release automation, see
- https://issues.redhat.com/browse/ROX-21868
- https://github.com/stackrox/stackrox/pull/9489
Timestamp and publisher are taken from the corresponding Stackrox releases.
- ~[ ] Updated documentation accordingly~
No testable changes.
=> ROX- 21868: backfill RELEASED_VERSIONS 

.github/workflows/collector-builder.yml, .github/workflows/collector-slim.yml
s390x build VMs were being created always, even when multi-arch builds were not requested as part of a PR. This simple makes sure that VM creation abides by the labels.
=> Only create s390x build VMs when theyre needed

collector/lib/SysdigService.cpp
Sometimes the timestamp of an event is far in the past or in the future. There is logging to catch this. This logging is already throttled so that it does not flood the log. However, the logging is still too much. This makes it so that the frequency of the logging is reduced.
~~- [ ] Updated documentation accordingly~~
~~ - [ ] Added unit tests~~
~~ - [ ] Added integration tests~~
~~ - [ ] Added regression tests~~
In addition to reviewing your code, reviewers **must** also review your testing instructions, and make sure they are …
=> Jv increase throttle time for time error

collector/container/rhtap-slim.Dockerfile
Neither of the removed files is present in the downstream image (checked `registry.redhat.io/advanced-cluster-security/rhacs-collector-slim-rhel8:4.3.2`).
These files are needed for open source compliance purposes in the upstream images which we build and distribute as a community product.
The files are absent in the downstream images because there we get _source containers_ automatically produced by the system. As Connor and I clarified at some point with a Red Hat lawyer, source containers fit the compliance and make `THIRD_PARTY_NOTICES` thing not required.
RHTAP/Konflux gives us source containers too, therefore the suggestion is to drop these files there too.
This follows up on my comments in earlier PR
* https://github.com/stackrox/collector/pull/1407/files#r1404290865
* …
=> chore: Remove licenses/third party notices from RHTAP collector-slim image

Makefile, builder/Dockerfile
Make it easier to create a builder container that can be connected locally through SSH.
- Builder runs sshd as entrypoint.
- The port is exposed only when LOCAL_SSH_PORT is set.
This is intended to ease the use of the builder in dev environments where SSH is used
to connect to the builder container.
=> Optional local builder access through SSH

collector/lib/KernelDriver.h, collector/lib/ProcessSignalFormatter.cpp
After temporary disabling trusted exepath [[1]] it turns out that original
implementation of exepath resolution wasn't reliable enough, producing flaky
test results. The usual failure looks like this:
* A process (usually runc) performs a chain of clones, potentially intertwined
with other activity we watch, e.g. closing pipes (runc is talking to clones
using pipes) or doing networking (as in some of our integration tests).
* As a last step this process does execve to perform some workload.
* The scap events we receive could be either our of order or even missing
sometimes. Exepath resolution relies on the presence of an enter event, thus
we got non-deterministic failures.
The reason for that is overlooked missing `sched_switch` event, which similar
to `procexit` became non-default one in …
=> Add switch event

collector/lib/SysdigService.cpp
After updating to vanilla Falco, Collector can see runc process with an absolute exepath. Filter it out as well.
The change is mostly visible in flaky tests, so CI is sufficient.
=> Improve runc filtering

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/CollectorService.cpp, collector/lib/ConnTracker.cpp, collector/lib/ConnTracker.h, collector/lib/EnvVar.h, collector/lib/NRadix.cpp, collector/lib/NRadix.h, collector/lib/NetworkConnection.cpp, collector/lib/NetworkConnection.h, collector/test/ConnTrackerTest.cpp, collector/test/NRadixTest.cpp, collector/test/NetworkConnectionTest.cpp, docs/references.md
Add a new Collector environment variable (ROX_IGNORE_NETWORKS) with a list of network prefixes that should be ignored by Collector;
Connections involving a matching remote address are not sent to Sensor.
The default value for the ignored network list is : 169.254.0.0/16
- ~~Added integration tests~~
**Testing done**
- With the default configuration: a connection to 223.42.0.2 is reported, and a connection to 169.254.0.2 is not.
- With an empty ignore-list: everything gets reported
- With 223.42.0.0/16 and 169.254.0.0/16 in the ignore-list: nothing reported.
=> ROX-21403: Option to ignore a set of networks.

collector/lib/CollectorConfig.cpp, docs/references.md
Link-local addresses are defined for IPv6 and was overlooked in #1511
=> ROX-21403: Add fe80::/10 to the networks ignored by default.

collector/collector.cpp, collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/KernelDriver.h, collector/test/HostHeuristicsTest.cpp, collector/test/NetworkStatusNotifierTest.cpp, docs/design-overview.md, docs/how-to-start.md, docs/references.md, integration-tests/suites/common/collector_manager.go, integration-tests/suites/config/config.go
Sets the default collection method to CORE_BPF for collector and the integration tests. Fixed unit tests that broke as a result of changing the default collection method to CORE_BPF. Also removed the hardfail config option for CORE_BPF. The code now behaves as though it is always true.
~~- [ ] Updated documentation accordingly~~
~~- [ ] Added unit tests~~
~~- [ ] Added integration tests~~
~~- [ ] Added regression tests~~
This changes the default collection method so testing it is not needed.
In addition to reviewing your code, …
=> Jv ebpf deprecation cleanup

.github/workflows/add-new-pr-to-oss-triaging.yml, .github/workflows/benchmarks.yml, .github/workflows/check-drivers-failures.yml, .github/workflows/collector-builder.yml, .github/workflows/collector-full.yml, .github/workflows/collector-slim.yml, .github/workflows/cpaas-sync-drivers.yml, .github/workflows/cpaas.yml, .github/workflows/drivers.yml, .github/workflows/gardenlinux-bumper.yml, .github/workflows/init.yml, .github/workflows/integration-test-containers.yml, .github/workflows/integration-tests-vm-type.yml, .github/workflows/lint.yml, .github/workflows/main.yml, .github/workflows/support-packages.yml, .github/workflows/upload-drivers.yml
This should be a cosmetic change that fixes the various warnings we currently get in CI about NodeJS versions. Functionality should be unaffected.
CI will be enough.
=> Bump actions versions to fix Node warnings

.github/workflows/benchmarks.yml, .github/workflows/check-drivers-failures.yml, .github/workflows/collector-full.yml, .github/workflows/cpaas-sync-drivers.yml, .github/workflows/cpaas.yml, .github/workflows/drivers.yml, .github/workflows/integration-test-containers.yml, .github/workflows/upload-drivers.yml
actions/upload-artifact@v4 no longer supports non-unique names. This PR ensures that cpaas driver failures are unique.
Run PR with cpaas label
=> Makes cpaas drivers failure artifacts unique for each architecture

integration-tests/suites/base.go, integration-tests/suites/common/executor.go
Sometimes Collector is either expected to fail or can fail during test setup or healthchecks. We want to retain any logs from the collector container, even in these cases.
The clean up function has been changed to unconditionally clean up Collector:
- Collector is not run with `--rm` so we can get the logs. For this reason, all the collector manager functions cope with a container that is not running (which makes the check in the clean up function redundant)
- The base class should be more thorough to ensure that all resources are cleaned up
CI primarily. Not able to strictly reproduce the problem seen [here](https://github.com/stackrox/collector/commit/507b1d8a3c9d861005fba71ac479fc0ebfdc0ec2/checks) but existence of logs in the right places should be enough
=> Ensure Collector is always cleaned up

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/SysdigService.cpp, docs/references.md
This value is important to manage memory consumption under process based loads, so expose it for configuration. The current value is in fact cut to 131072, and to address memory consumption concerns I've set the current size to the half of this value. 
Local testing.
=> Make thread cache size configurable

collector/lib/CollectorStatsExporter.cpp, collector/lib/Sysdig.h, collector/lib/SysdigService.cpp, docs/troubleshooting.md
This implements a simple gauge to report the current size of the thread cache. It is sampled
by the CollectorStatsExporter every 5s.
fixes #1456
=> New metric to observe the thread cache size

.tekton/collector-slim-pull-request.yaml, .tekton/collector-slim-push.yaml, collector/container/konflux-slim.Dockerfile
- RHTAP was renamed to Konflux
- remove libinsp wrapper cleanup according to https://github.com/stackrox/collector/pull/1441#discussion_r1484450706 
=> chore: rename RHTAP references to Konflux

.tekton/collector-pull-request.yaml, .tekton/collector-push.yaml
Enabling source image builds for collector-full on Konflux.
Passing Konflux build is sufficient.
=> ROX-20900: enable source image builds for collector-full on Konflux

collector/lib/CollectorConfig.h
Limit the default amount of threads cached further, to make sure we're on the safe side. Benchmarks show that the CPU overhead is minimal in comparison with EBPF, as CO-RE BPF brings certain performance improvements that balance it out.
=> Reduce sinsp_thread_cache_size

ansible/ansible.cfg
Since integration tests are invoked from the ansible directory, they pick up configuration from `ansible.cfg`. Currently, it says that the stdout_callback has to be selective, which means only failed steps are going to be shown. An annoying consequence is that stdout will not be exposed even for failing steps (unless handled explicitly), which makes troubleshooting of some steps harder. Make it debug and verify if this will produce too much logs.
Local testing for failing steps. Otherwise CI is sufficient.
=> Use debug for stdout_callback

.github/workflows/drivers.yml
Github Actions will skip a job if all of its dependencies are also skipped. This is ordinarily fine, but for release branches we don't want the drivers build to run, but we do want the full builds to run.
This adds a sentinel job in the drivers workflow to ensure that even if the driver build itself is skipped, the workflow runs at least one job, and therefore the full builds will also run.
This will not run on this PR, but I have tested the mechanism on one of my own repositories and it works: https://github.com/Stringy/wisdom/pull/10
Tested on my own repo here https://github.com/Stringy/wisdom/pull/10
=> Adds a sentinel step to drivers build for release branches

ansible/ansible.cfg
We frequently observe issues with spinning up new test VMs, that manifests itself as a non-reachable host. Try to reduce the problem via increasing number of retries (the default value seems to be 0 [[1]]).
[1]: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/ssh_connection.html#parameter-reconnection_retries
=> Add retries

.github/workflows/gardenlinux-bumper.yml
This should fix an error with a change to a GH API that broke the action.
See https://newreleases.io/project/github/peter-evans/create-pull-request/release/v6.0.1 for more details.
=> Update peter-evans/create-pull-request action to latest version

.github/workflows/check-drivers-failures.yml, .github/workflows/collector-full.yml, .github/workflows/drivers.yml, .github/workflows/main.yml, .github/workflows/upload-drivers.yml
When the various GHA actions were updated, I missed a couple of breaking changes in the drivers build, specifically that multiple artifacts with the same name are no longer supported. This PR handles that case by making the names unique and ensuring they're downloaded appropriately.
CI with multiple driver runners should do it.
=> Fixes duplicate driver artifacts when build uses multiple GHA runners

kernel-modules/BLOCKLIST
6.7 fix is only available from 2.9.1 and on, for now.
=> Block probes <=2.9.0 for linux >=6.7

.github/workflows/collector-slim.yml
This separation should make it a little easier to follow the workflows, since each of them will only have the steps needed for the type of build taking place. Additional motivation for this is in having better handling of external PRs, since a PR from a fork will not have the required credentials to create a remote VM in our GCP projects.
For the time being, this is very much some personal investigating and team feedback is very much needed.
=> Split slim builds in local gha runner and remote vm

.github/actions/support-package-metadata-json/metadata.py, .github/workflows/support-packages.yml, kernel-modules/support-packages/04-create-support-packages.sh, kernel-modules/support-packages/utils.sh
As part of the 4.4 release, upstream drivers are being removed from full images as well as support packages, relying instead on downstream built drivers.
=> ROX-18383: remove upstream drivers from support packages

collector/CMakeLists.txt, collector/lib/CMakeLists.txt, collector/lib/CollectorService.cpp, collector/lib/CollectorService.h, collector/lib/CollectorStatsExporter.cpp, collector/lib/CollectorStatsExporter.h, collector/lib/Control.h, collector/lib/DriverCandidates.cpp, collector/lib/GetKernelObject.cpp, collector/lib/GetStatus.cpp, collector/lib/GetStatus.h, collector/lib/KernelDriver.h, collector/lib/NetworkSignalHandler.cpp, collector/lib/NetworkSignalHandler.h, collector/lib/Process.cpp, collector/lib/Process.h, collector/lib/ProcessSignalFormatter.h, collector/lib/ProcessSignalHandler.h, collector/lib/SelfCheckHandler.h, collector/lib/Utility.h, collector/lib/system-inspector/EventExtractor.cpp, collector/lib/system-inspector/EventExtractor.h, collector/lib/system-inspector/Service.cpp, collector/lib/system-inspector/Service.h, collector/lib/system-inspector/SystemInspector.h, collector/test/SystemInspectorServiceTest.cpp, docs/design-overview.md, docs/troubleshooting.md
This is a long due change, all mentions of Sysdig and Falco have been replaced by a more generic system_inspector name. No functional change has been made, the PR is purely organizational.
CI should be enough, since things are just being shuffled around.
=> Remove all mentions of Sysdig and Falco in our codebase

collector/lib/AbortHandler.cpp
Fix annoying small warning about copying one-by-off.
=> Fix write warning in abort handler

kernel-modules/support-packages/utils.sh
The version checking was broken which led to very small support packages for module versions that should include both up and downstream kernels. This PR fixes that check.
=> ROX-23497 Fixes version comparison for support packages

collector/lib/HostHeuristics.cpp, collector/lib/HostInfo.cpp, collector/lib/HostInfo.h
The modern probe fails to load on RHEL 8.6 + Power.
Temporarily fallback on ebpf in this particular case while we troubleshoot this issue.
=> ROX-23499: Force EBPF when Power + OCP4.12

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/HostConfig.h, collector/lib/HostHeuristics.cpp, collector/lib/HostInfo.cpp, collector/lib/HostInfo.h, collector/test/CollectorConfigTest.cpp, docs/references.md
Allow to specify the upper limit for all ring buffers together, to avoid issues when a node has lots of CPUs, and for every single one buffer will be allocated, eventually running out of memory. The limit could be specified via ROX_COLLECTOR_SINSP_TOTAL_BUFFER_SIZE, but the default value of 512Mi should be good enough for the basic case, where the Collector DaemonSet memory limit is 1Gi.
If at the configuration phase Collector figures out that it can't match specified limit, sinsp_cpu_per_buffer_ will be adjusted to fit under the allowed threshold.
=> Limit total ring buffer size

collector/container/konflux.Dockerfile
This updates product name from StackRox to RHACS.
Spotted while reviewing https://gitlab.cee.redhat.com/stackrox/rhacs-midstream/-/merge_requests/2862
It may happen that we eventually will have to customize labels when we build OSS version on Konflux but we aren't there yet. For now it's important to identify containers as part of RHACS.
- ~~[ ] Added unit tests~~
- ~~[ ] Added integration tests~~
- ~~[ ] Added regression tests~~
Only CI.
=> chore: Update product name in Konflux image labels

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h
Fix mixed up initial values. Add one more sanity check to not go into calculations of no cpu-per-buffer is even requested.
=> Fix mixed up total/single buffer size

integration-tests/README.md, integration-tests/pkg/collector/collector.go, integration-tests/pkg/collector/collector_docker.go, integration-tests/pkg/collector/collector_k8s.go, integration-tests/pkg/common/utils.go, integration-tests/pkg/executor/executor_k8s.go, integration-tests/suites/k8s_namespace.go
#1606 added some basic K8S based tests. Because the amount of changes needed for those to work were significant, I decided to postpone adding anything that was not absolutely necessary for the tests to work. Now that those have been merged to master, it's a great time to improve them a bit and make them easier to work with.
This PR makes it so alongside the collector logs for the tests, the events for the involved namespaces and the pod configuration used by pods are also dumped in order to provide more details when a deeper issue arises and no logs are available. The one "downside" to the approach is the dumped events and configuration are in JSON format, since that seemed like the easiest to get working, using `jq` and/or `grep` should make it relatively easy to get any required …
=> Collect K8S events and pod configuration on K8S based tests

integration-tests/pkg/mock_sensor/expect_proc.go
Calling time.After in a for-select loop causes a new channel to be spawned with a new timeout, so using it alongside a ticker causes the timeout to never occur. Assigning the channel to a separate variable and using that on the loop should take care of the issue. See [this SO answer](https://stackoverflow.com/a/66003389) for more details.
Fix is simple enough that shouldn't need testing outside CI.
=> Prevent waiting infinitely for processes

collector/container/konflux.Dockerfile
USDT support requires systemtap, but Konflux setup doesn't use the builder image. Add the dependency directly.
=> Add systemtap to Konflux

.github/workflows/k8s-integration-tests.yml, integration-tests/pkg/collector/collector_k8s.go, integration-tests/pkg/executor/executor_k8s.go, integration-tests/suites/k8s_namespace.go
Listing namespace events is failing to get all events, limiting how useful they can be when debugging issues on the K8S based tests. This change makes it so goroutines are spawned with event watchers and events are continuously piped into output files, from the testing I've done this seems to be the most reliable method to always get useful events dumped.
There's also a minor refactor on the `k8s_namespace.go` file so that operations related to the target namespace are done closer together.
The trigger for this change was a CI run on the master branch that had no events on the output log, I managed to reproduce a similar error by attempting to run with a collector image that doesn't exist, causing it to go into pull backoff error. With this change the watchers still dump events stating …
=> Use event watchers for namespace events

collector/CMakeLists.txt, collector/lib/ProcessSignalFormatter.cpp, collector/lib/system-inspector/EventExtractor.h, collector/lib/system-inspector/Service.cpp, collector/test/ProcessSignalFormatterTest.cpp
In order to reduce memory footprint, enable slim threadinfo option.
=> Enable slim threadinfo option

kernel-modules/BLOCKLIST
Should fix the drivers failures on master.
=> Add RHEL 9.4 block for legacy module versions

collector/lib/CollectorConfig.cpp, collector/lib/ContainerMetadata.cpp, collector/lib/ContainerMetadata.h, collector/lib/NetworkSignalHandler.cpp, collector/lib/NetworkSignalHandler.h, collector/lib/Process.cpp, collector/lib/ProcessSignalFormatter.cpp, collector/lib/ProcessSignalFormatter.h, collector/lib/ProcessSignalHandler.cpp, collector/lib/ProcessSignalHandler.h, collector/lib/ProtoSignalFormatter.h, collector/lib/SelfCheckHandler.cpp, collector/lib/SelfCheckHandler.h, collector/lib/SignalHandler.h, collector/lib/Utility.cpp, collector/lib/Utility.h, collector/lib/system-inspector/Service.cpp, collector/lib/system-inspector/Service.h, collector/test/SystemInspectorServiceTest.cpp
This is to avoid unexpected conflicts when updating falco, and because we plan to decouple Collector from the probe implementation (makes it explicit which parts make direct use of types).
- Everywhere possible, the `sinsp.h` includes have been moved from the header side to the implementation (.cpp)
- Only EventExtractor was kept with this include in its own header, as its interface is rooted in falco types.
- Users of EventExtractor then forward declare it and include the EventExtractor header from their implementation.
=> Limit inclusion forwarding of the falco headers

.github/workflows/collector-full.yml
This is needed because the number of probes have exceeded the configured size. The master branch has an improved partitioning script that auto-adjusts this value, but I don't think it's worth the hassle to backport it.
CI with `build-full-images` label should be enough.
=> Bump layers used on the full image to 7

collector/lib/CollectorService.cpp, collector/lib/NetworkStatusInspector.cpp, collector/lib/NetworkStatusInspector.h, docs/references.md, docs/troubleshooting.md, integration-tests/integration_test.go, integration-tests/suites/http_endpoint_availability.go
Adds a pair of web endpoints to retrieve the internal network tables of Collector (normalized and deduplicated, same as what is sent to Sensor).
The endpoints are activated by an environment variable (~~`ROX_COLLECTOR_ENABLE_INTROSPECTION`~~ `DEBUG_ENABLE_INTROSPECTION`). The default disabled.
=> Network introspection endpoints

.github/workflows/cpaas.yml
The check-drivers-build-failures notification was failing because it didn't have secrets for the slack webhook. This PR simply passes those through to the workflow.
=> Inherit secrets for driver build failure check

.tekton/collector-pull-request.yaml, .tekton/collector-push.yaml, .tekton/collector-slim-pull-request.yaml, .tekton/collector-slim-push.yaml
Switch to push images to `quay.io/rhacs-eng`.
Creates images like:
- `quay.io/rhacs-eng/collector:3.18.x-231-g2c316751d5-fast-latest`
- `quay.io/rhacs-eng/collector:3.18.x-231-g2c316751d5-fast-slim`
Konflux passing with correct image names is sufficient.
=> ROX-22474: push Konflux images to quay.io/rhacs-eng

.github/workflows/k8s-integration-tests.yml, ansible/README.md, ansible/k8s-integration-tests.yml, ansible/requirements.txt, ansible/requirements.yml, ansible/roles/kind-load-image/tasks/docker.yml, ansible/roles/kind-load-image/tasks/main.yml, ansible/roles/kind-load-image/tasks/podman.yml
This change was triggered by an issue on CI where the k8s based integration tests were failing to upload the collector image to the kind cluster. The culprit for this error was a breaking change on the python requests package, see:
- https://github.com/docker/docker-py/issues/3256
- https://github.com/docker/docker-py/pull/3257
For the time being and until a new release of the docker Python SDK is uploaded, pinning requests to version 2.31.0 seems to fix the issue.
While trying to debug the issue locally with podman v5 it was found out the community.docker module is incompatible. In order to work around this, a new role was added so people can chose to upload images from docker or podman via the `container_engine` variable. Ideally we would have a way to decide which to use automatically, …
=> Fixes for k8s based integration tests

.github/workflows/collector.yml, .github/workflows/cpaas.yml, ansible/group_vars/all.yml, ansible/roles/create-vm/tasks/main.yml, collector/lib/HostHeuristics.cpp, kernel-modules/build/prepare-src
Removes last remaining bits of eBPF power workarounds
=> eBPF turn-off without Power

kernel-modules/BLOCKLIST
Kernel modules for newer EL 8 and 9 kernels for 3.74 are failing with the following error message:
```
============================================================================
Failed to build mod probe
Module version: 2.3.0
Kernel version: 4.18.0-553.el8_10.x86_64
/kobuild-tmp/versions-src/2.3.0/main.c: In function 'scap_init':
/kobuild-tmp/versions-src/2.3.0/main.c:3245:23: error: assignment to 'char * (*)(const struct device *, umode_t *)' {aka 'char * (*)(const struct device *, short unsigned int *)'} from incompatible pointer type 'char * (*)(struct device *, umode_t *)' {aka 'char * (*)(struct device *, short unsigned int *)'} [-Werror=incompatible-pointer-types]
g_ppm_class->devnode = ppm_devnode;
^
In file included from /kobuild-tmp/versions-src/2.3.0/ppm_fillers.c:100: …
```
=> Skip EL 8 and 9 kernel modules for 3.74

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/system-inspector/Service.cpp, docs/troubleshooting.md, integration-tests/suites/k8s_namespace.go
Since the initial implementation, we've expanded the reach for the runtime filters and it has been renamed to runtime configuration, so we should rename some part of our code to match this.
CI should suffice.
=> Rename runtime filters to config

RELEASED_VERSIONS
This change mocks a release for the 2.9.1 drivers and reenables driver builds on the release branch. This is done to fix a failure to build support-packages in the master branch. The fix is just a workaround, but because driver deprecation and removal is coming soon, I think this should be good enough.
CI is enough.
=> Build 2.9.1 drivers

.github/workflows/main-drivers.yml, .github/workflows/support-packages.yml, kernel-modules/support-packages/04-create-support-packages.sh, kernel-modules/support-packages/utils.sh
Following eBPF turn off, this will prevent support package creation for newer module versions.
=> Don't build support packages for 2.10.0 and newer

.github/workflows/integration-tests.yml, .github/workflows/k8s-integration-tests.yml, .github/workflows/konflux-tests.yml, .github/workflows/konflux.yml
Since konflux seems to be coming along quite nicely and the recent changes have made it so only one image is built for it, it seems like a good moment to start properly testing the images in our CI. With this change tests will be run on the konflux built images on master, tags and PRs for branches that contain the words `konflux` or `rhtap`.
=> Run integration tests on konflux built images

.tekton/collector-build.yaml
=> ROX-20230: bump image expiration on Konflux to 1 year

ansible/requirements.txt
Ansible 10 has removed support for python 3.6 on remote systems, which also happens to be the version shipped with RHEL 8.  In order to get our tests up and running again, we can politely ask pip to install a version less than 10 for ansible.
References:
- ansible-core removes support for Python 3.6 on remote systems: https://github.com/ansible/ansible/blob/v2.17.0/changelogs/CHANGELOG-v2.17.rst#removed-features-previously-deprecated
- Failing tests on RHEL 8: https://github.com/stackrox/collector/actions/runs/9369754292/job/25829475272
Validate the RHEL 8 tests now work correctly.
=> Pin ansible version to allow RHEL 8 tests to work

collector/container/konflux.Dockerfile
Per title, plus a few cosmetics.
This isn't needed:
Did not add these:
=> ROX-20236: Set `release` Dockerfile label explicitly

kernel-modules/BLOCKLIST
eBPF drivers for RHEL 9.4 should be supported starting with version 2.9.1
Run with `build-legacy-probes` label.
=> Unblock drivers for RHEL 9.4+ on 2.9.1

collector/lib/NetworkStatusInspector.cpp, collector/lib/NetworkStatusInspector.h, docs/troubleshooting.md
With normalization always enabled, the introspection API cannot be used to retrieve all IP addresses. So we add a parameter to disable it.
Link to the updated documentation: https://github.com/stackrox/collector/blob/ovalenti/conn_introspection_no_normalize/docs/troubleshooting.md#network-endpoint
=> Control normalization in network introspection API

.github/workflows/main-drivers.yml
Support package workflow handles its own notifications, so remove it from the main driver workflow to avoid double notifications.
=> Remove support packages from driver workflow notification

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/test/CollectorConfigTest.cpp, docs/references.md
It turns out making many CPU cores working with a single ringbuf has a potential deadlock hazard, especially visible on RT kernels. To avoid even a slightest danger, reduce ringbuf size instead. In the new scenario if we do not fit into the total ringbuf size, the size of each individual ringbuf will be adjusted and aligned for readability.
=> Adjust buffer size instead of cpu-per-core

collector/lib/CollectorConfig.cpp, collector/lib/CollectorStatsExporter.cpp, collector/lib/GetStatus.cpp, collector/lib/system-inspector/Service.cpp, collector/lib/system-inspector/SystemInspector.h, docs/troubleshooting.md
Use Falco's stats v2 to zoom into the events drop metrics and split it into drops due to full buffers vs due to full thread cache.
There was some concern enabling the stats v2 portion of Falco would cause some unwanted procfs scraping from the following functions:
- https://github.com/stackrox/falcosecurity-libs/blob/a283653ee897a17c77d781931170962494188bc3/userspace/libsinsp/metrics_collector.cpp#L241
- https://github.com/stackrox/falcosecurity-libs/blob/a283653ee897a17c77d781931170962494188bc3/userspace/libsinsp/metrics_collector.cpp#L349
- https://github.com/stackrox/falcosecurity-libs/blob/a283653ee897a17c77d781931170962494188bc3/userspace/libsinsp/metrics_collector.cpp#L449
However, after inspecting the code and testing with GDB, it became clear those functions are only called from …
=> Enable stats v2

ansible/group_vars/all.yml
As explained in ROX-24938, collector has been unable to run on cos-dev VMs due to a verifier error for the last couple of days. Until we can look into the issue, we should disable the integration test from running so we can keep our CI green and happy.
Run with the all integration tests label, cos-dev should not be created.
=> Disabling the COS dev tests until we can look into the verifier error

ansible/group_vars/all.yml, ansible/roles/provision-vm/tasks/redhat.yml
After disabling of the troublesome repo, some other RHEL based tests have been failing because the repo is not actually available in them. This attempts to narrow down the `dnf config-manager --disable` command to the one GCP family that was showing the issue.
=> Narrow down disabling of RHUI repo to the one family that is failing

ansible/roles/create-all-vms/tasks/by-image.yml
Power VMs get a separate naming convention because they require to have less than 47 characters and are the only image based VM that isn't explicit enough (rhcos specifies version and only uses x86, similar situation with garden linux).
Additionally, the collection method portion of the names has been dropped, since we only have a single supported driver.
Running with the multiarch builds and all integration tests labels should be enough.
=> Simplify VM naming scheme for testing

ansible/roles/provision-vm/tasks/redhat.yml
Updating the dnf cache by running makecache might help reduce some timeout errors we've been having in CI.
CI is enough.
=> Update dnf cache before installing packages

ansible/roles/create-vm/tasks/create-ppc64le-vm.yml
WARNING health status was added in an attempt to speed up ppc64le provisioning by shortcutting the creation process, allowing us to try to communicate with the VM before IBM cloud says it's in a stable condition.
This worked in testing on the original PR, but has been failing on master. This PR undoes the change in order to maintain some CI stability. 
For more details, ref the [Confluence …
=> Remove WARNING health status for ppc64le VMs

builder/install/30-cares.sh
The previous link pointed at an non-existent location, possibly because they've moved stuff around on their website. This links directly to the github release page (which is where the website links to now)
I've built the builder locally, and successfully, a CI rebuild will prove its success.
=> Switches c-ares download to github release link

.github/workflows/integration-test-containers.yml
When the image isn't rebuilt, the default tag is chosen, but one instance of the default tag was incorrect, causing failing tests.
=> Fixes test image tag default

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/CollectorService.cpp, collector/lib/ConnTracker.cpp, collector/lib/ConnTracker.h, collector/test/ConnTrackerTest.cpp, docs/references.md
This adds an environment variable providing Collector with a list of subnets to never aggregate (`ROX_NON_AGGREGATED_NETWORKS`).
As a side effect, this can be used to expand the list of standard private network prefixes with new ones.
- deployed a K8S cluster with 34.228.224.0/24 as the service CIDR
- install ACS 4.4
- the network graph shows no connection to `central-db`
- update the collector image to the one produced by this PR. Set `ROX_NON_AGGREGATED_NETWORKS=34.228.224.0/24`
- the network graph then shows `central` connecting to `central-db`
=> Instruct Collector to not aggregate some subnets

collector/lib/Logging.cpp
The logs coming from libbpf are marked by Falco as DEBUG logs, but they are extremely verbose (>35000 lines) and contain little information useful to general debugging of Collector. This PR downgrades those logs to TRACE, so they are still available for debugging of CORE_BPF loading, but not always written to our usual test logs or under typical testing load.
=> Downgrade libbpf DEBUG logs to TRACE

collector/lib/Logging.cpp
The check for log level needs to happen after we've downgraded them to trace. In order to prevent looking for the `libbpf:` prefix on every log line issued by Falco, we first check if we are running in debug mode, limiting the impact to systems that are actively being debugged.
This bug was introduced by a change I suggested in https://github.com/stackrox/collector/pull/1738#discussion_r1679500633
=> Small fix to libbpf log downgrading

.github/workflows/integration-tests.yml, ansible/group_vars/all.yml, ansible/roles/provision-vm/tasks/main.yml
The latest nightly failed because GHA workflow number added a digit and pushed the VM name over the limit of characters allowed by GCP. Simple fix is to just use a shorter name for the family like we already do for Fedora CoreOS on Arm.
Run CI with the `run-multiarch-builds` and check all tests create VMs and run as expected.
=> Shorten ubuntu arm name so GCP doesn't complain of VM name too long

builder/install/30-cares.sh, collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/CollectorService.cpp, collector/lib/ConnTracker.cpp, collector/lib/ConnTracker.h, collector/test/ConnTrackerTest.cpp, docs/references.md
This is a backport of the #1639 PR for a 4.4 patch release. See details of the change in that PR.
#1733 is also backported, otherwise the builder just fails to run.
=> Backport network flow aggregation

.github/workflows/konflux-tests.yml
This change prevents VMs used to test konflux images from having name collisions with the ones used by master.
CI should be enough to check the names used on the VMs now have `konf` as part of their name.
=> Use a different job tag for konflux tests

.github/workflows/konflux.yml
Currently, konflux is not being run on release branches and tags, so the associated tests will always fail with a timeout waiting for the images to become available.
If we start using konflux on these branches and tags, adding back the tests should be pretty straightforward.
This is a simple change, no testing should be needed.
=> Stop running konflux tests on release branches and tags

ansible/ci/group_vars/all.yml, ansible/ci/inventory_gcp.yml, ansible/dev/group_vars/all.yml, ansible/dev/inventory_gcp.yml, ansible/roles/create-all-vms/tasks/by-family.yml, ansible/roles/create-all-vms/tasks/main.yml
Remove collection method (unused)
Remove collector- prefix (it's implied)
Truncate family name to max 16 characters
Hash and truncate the job id suffix
=> Simplify GCP VM name generation

.github/workflows/integration-tests.yml
We split the set of integration tests run on PRs due to some of them taking a long time and some flakiness. Since we did this split, the flakiness has gone down as well as the time taken to run the tests, so we might as well always run the full set.
CI is enough
=> Run all amd64 integration tests on PRs

collector/container/scripts/bootstrap.sh, collector/lib/HostHeuristics.cpp, collector/lib/HostInfo.h, collector/lib/KernelDriver.h, collector/lib/system-inspector/Service.cpp, collector/test/HostHeuristicsTest.cpp
Now we live in a post-eBPF world, the log messages in the heuristics can be confusing. They have been reworded to suggest that NO_COLLECTION can be used, since we do not have another collection method to switch to if any of these checks fail.
Also includes some minor cleanup in the unit tests and bootstrap shell script (which contained references to kernel modules... remember them?)
For more details, ref the …
=> Removes eBPF logging references and eBPF switching host heuristics

.github/workflows/integration-test-containers.yml, integration-tests/Dockerfile, integration-tests/pkg/types/network.go, integration-tests/suites/repeated_network_flow.go
#1755 bumped the go version required for the integration tests, a similar bump is needed to the base version used for the container.
Ensure the integration tests container is built correctly.
=> Bump golang version used for integration tests

.github/workflows/konflux.yml, .tekton/collector-build.yaml
This should enable Konflux builds from release branches for the case when [COLLECTOR_VERSION](https://github.com/stackrox/stackrox/blob/master/COLLECTOR_VERSION) points to a tag/commit that was on a release branch, not on `master`.
Prerequisite for ROX-24468
Available CEL functions are here <https://github.com/google/cel-spec/blob/master/doc/langdef.md#list-of-standard-definitions>.
No contributions.
None, only CI.
=> chore: Add `^release-` branches for on-push Konflux builds

.tekton/collector-component-pipeline.yaml
See ROX-25620 for context.
Used the following simple script to figure out new tasks digests:
```bash
$ cat figure-digest.sh
#!/usr/bin/env bash
image="$1"
podman pull "$image"
digest="$(podman inspect "$image" | jq -r '.[0].Digest')"
echo "$image@$digest"
echo -n "$image@$digest" | xclip -selection c
```
No automated tests.
Only CI.
=> ROX-25620: Switch Konflux tasks to new repos

.github/actions/support-package-metadata/create-metadata-dir.sh, kernel-modules/support-packages/03-group-by-module-version.sh
#1773 removed the `MODULE_VERSION` file, so when syncing support packages from downstream, we should skip versions that don't have this file.
Run with `run-cpaas-steps` label.
=> Check for existence of MODULE_VERSION file

integration-tests/integration_test.go, integration-tests/pkg/config/config.go, integration-tests/pkg/config/env.go, integration-tests/pkg/executor/executor.go, integration-tests/pkg/executor/executor_docker.go, integration-tests/suites/base.go
The SSH and GCP command builders are no longer used. This PR simply removes them. CI testing should be sufficient.
=> Removes SSH and GCP command builders

.github/workflows/konflux-tests.yml, .tekton/collector-build.yaml
I noticed that GHA builds were failing on me https://github.com/stackrox/collector/actions/runs/10375095581/job/28724093219
This should fix it.
GHA should pass.
=> build: Adjust timeout waiting for Konflux images

ansible/roles/run-test-target/tasks/test-collection-method.yml, integration-tests/integration_test.go, integration-tests/pkg/common/utils.go, integration-tests/pkg/executor/retry.go, integration-tests/pkg/mock_sensor/expect_conn.go, integration-tests/pkg/mock_sensor/server.go, integration-tests/pkg/types/endpoint.go, integration-tests/pkg/types/listen_address.go, integration-tests/pkg/types/process_originator.go, integration-tests/suites/async_connections.go, integration-tests/suites/connections_and_endpoints.go, integration-tests/suites/duplicate_endpoints.go, integration-tests/suites/gperftools.go, integration-tests/suites/listening_ports.go, integration-tests/suites/process_network.go, integration-tests/suites/procfs_scraper.go, integration-tests/suites/repeated_network_flow.go, integration-tests/suites/socat.go, integration-tests/suites/symlink_process.go
The ExpectConnections and ExpectEndpoints are incorrectly succeeding due to a logic bug in in the event filtering:
- the caller specifies a set of expected connections or endpoints
- the function attempts filter that list to get a list of entities that have not been seen
- the filter condition is backwards, instead giving a list of entities that have been seen
- At this early stage in the function, no events have been seen, but the function incorrectly believes that all events have been seen and returns success.
=> ROX-25788: fix integration tests handling of connections and endpoints

.tekton/collector-component-pipeline.yaml
If we feed the image manifest, we only need one deprecated-image-check task.
https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1723738910783329
Konflux CI passes.
=> ROX-25623: reduce deprecated-image-check by feeding manifest

ansible/dev/group_vars/all.yml, ansible/dev/inventory_gcp.yml
To make GCP VMs easier to differentiate, this PR prefixes the (local) username to the VM name upon creation. 
Tested locally.
Regarding VM name length limits, this won't affect CI VMs at all, and will break locally a fair while before it breaks for VMs (though with the recent changes to the naming convention, we have a significant buffer zone before limits become a problem again)
=> Add username to dev VMs to make it easier to differentiate them

docs/falco-update.md
With the removal of the MODULE_VERSION file in #1773 our handling of the falco libs fork is somewhat outdated, since now there is no module version to use as a guideline. Instead, I'm proposing that we start using the upstream version we are based on as part of our branching strategy.
With this new approach, branches with our changes will be of the form M.m.p-stackrox, with M.m.p being the version numbers for the upstream libs tag the branch is based on.
This is a documentation only PR, no testing is necessary.
=> Update Falco bumping instructions

ansible/group_vars/all.yml
Now that the verifier issue that was present on newer cos kernels has been resolved by #1812, we should be able to add back the dev version of this distro to our integration tests.
CI is enough.
=> Reenable cos-dev tests

.github/workflows/cpaas-sync-drivers.yml
This is a minor change, we are getting some error message on the upload support packages steps from the CPaaS workflows because the google-github-actions/upload-cloud-storage action expects a gcloudignore to be present by default. Since we don't expect to process this kind of file, we just set the option to false on all occurrences of the action.
Without this change the actions still worked correctly, this is merely to get rid of the annoying error messages in the CI output.
Examples of the errors can be found here: https://github.com/stackrox/collector/actions/runs/10609617180/job/29405734430
=> Do not process gcloudignore files when uploading support-packages

collector/collector.cpp, collector/container/Dockerfile, collector/container/konflux.Dockerfile, collector/lib/CollectorArgs.cpp, collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/EnvVar.h, collector/lib/GRPC.cpp, collector/lib/GRPC.h, collector/lib/TlsConfig.h, collector/test/CollectorArgs_test.cpp, integration-tests/pkg/collector/collector_docker.go
This change makes it so environment variables can be used to configure all arguments that can be provided via CLI parameters. This should in turn make configuring collector in k8s easier and simplify the command
to be used in our dockerfiles.
In order to prevent as many breaking changes as possible, CLI arguments will take precedence over environment variables. For TLS certificates a variable was added for specifying a directory holding the ca.pem,
cert.pem and key.pem files, and three other variables were added to be able to override the location of each of the files or explicitly setting all three if needed.
New environment variables added:
- ROX_COLLECTOR_LOG_LEVEL: Sets the log level to be used.
- ROX_COLLECTOR_SCRAPE_INTERVAL: Set the scrapping interval in seconds.
- …
=> Provide environment variable alternatives to CLI arguments

collector/container/konflux.Dockerfile
PR #1814 removed the scripts used by collector to run, making it possible for it to be run directly. The Konflux build is still attempting to copy the scripts directory into the image even though it doesn't exist anymore, so we should remove that line from the dockerfile.
As an additional cleanup, since we have been linking falco statically for some time now, there's no need to call ldconfig anymore.
=> Fix Konflux build after collector scripts removal

collector/container/konflux.Dockerfile
Yet another mistake from #1814. The version of collector is now hardcoded into the binary, but that needs to be set at compile time, which was not being done in konflux builds. The label with the version was being set properly, this only affects collector printing its version to the logs.
=> Add collector version to compilation step

.tekton/collector-component-pipeline.yaml, collector/container/konflux.Dockerfile
Adds ecosystem cert preflight check to Konflux pipeline.
Passing Konflux CI is sufficient.
=> ROX-25723: add ecosystem preflight check

.gitignore, Makefile, Makefile-constants.mk, collector/CMakeLists.txt, collector/Makefile, collector/Version.h.in, collector/collector.cpp, collector/container/Dockerfile, collector/container/konflux.Dockerfile, collector/lib/CollectorVersion.h.in, docs/how-to-start.md, integration-tests/pkg/collector/collector_k8s.go, integration-tests/pkg/config/config.go, integration-tests/pkg/config/env.go
- add back json array format for collector entrypoint
- rename collector version file Version.h to CollectorVersion.h to prevent conflicts with libsinsp/version.h on case-insensitive build envs (aka, local mac argh!)
- auto-detect platform arch
- specify arch in builder image name and cmake-dir
- remove references to `COLLECTOR_PRE_ARGUMENTS`
works locally on mac aarch64
=> Local dev fixes

Makefile-constants.mk
The removed lines depend on the docker CLI specifically, it does not work when podman is aliased to docker. Instead, we can just use uname -m and replace it with sed, effectively making it work on any linux system.
=> Determine host architecture without using docker

collector/lib/system-inspector/Service.cpp
=> refactor if-statements for better readability 

Makefile, docs/how-to-start.md
Add `init-githooks` Makefile target similar to stackrox.
=> Add `init-githooks` Makefile target

.konflux/scripts/subscription-manager-bro.sh, .tekton/collector-component-pipeline.yaml
See the ticket's description. The key is already set up.
If things still build in Konflux, all is fine.
=> ROX-26047: Switch to prod subscription-manager activation key

collector/container/konflux.Dockerfile
See related ticket.
No automated testing changes.
Ensuring CI is green.
=> ROX-25565: Fail Konflux builds if required ARGs aren't provided

.clang-format, .github/workflows/lint.yml, collector/lib/CollectorStats.h, collector/lib/DuplexGRPC.h, collector/lib/ProcfsScraper.cpp, collector/lib/SignalServiceClient.cpp, collector/lib/SignalServiceClient.h, collector/test/HostHeuristicsTest.cpp, integration-tests/container/perf/scripts/init.sh
Enable expand brackets clang-format for better readability.
https://github.com/stackrox/collector/pull/1851
=> Enable InsertBraces in clang-format

ansible/roles/run-test-target/tasks/main.yml, integration-tests/pkg/config/config.go, integration-tests/pkg/config/env.go, integration-tests/suites/base.go
Nothing too exciting.
- Always use core_bpf in ansible playbooks
- remove unused/unset InstanceType from test config
=> Minor tidy up in tests and ansible

.github/workflows/benchmarks.yml, .github/workflows/check-drivers-failures.yml, .github/workflows/collector-builder.yml, .github/workflows/collector.yml, .github/workflows/cpaas-sync-drivers.yml, .github/workflows/cpaas.yml, .github/workflows/gardenlinux-bumper.yml, .github/workflows/init.yml, .github/workflows/integration-test-containers.yml, .github/workflows/integration-tests-vm-type.yml, .github/workflows/integration-tests.yml, .github/workflows/k8s-integration-tests.yml, .github/workflows/konflux.yml, .github/workflows/main.yml, ansible/Makefile
Having runners configured to `ubuntu-latest` means that the underlying VM could be updated to a newer version without us knowing. This should only be a problem when a new LTS version of Ubuntu is made the default for GHA and shouldn't be a major problem for us, since we mostly use generic tools pre-installed on all runners but, just in case, we should be explicit about what version of runner we want to use.
Run as many workflows as possible and checked none of them is broken.
=> Pin GHA runners to ubuntu-24.04

collector/lib/ProcessSignalFormatter.cpp, collector/lib/Utility.cpp, collector/lib/Utility.h, collector/test/UtilityTest.cpp
Containers can produce non-UTF8 process names or paths. We want to prevent this from causing issues in protobuf, which doesn't like it at all.
As a quick workaround, we reuse `google::protobuf::internal::UTF8CoerceToStructurallyValid` to replace any invalid sequence with '?'.
In order to minimize string copies in the "no modifications required" case, we introduce a Holder<> class to either point to the original unmodified string, or to an altered copy of it.
=> ROX-26025: Sanitize UTF-8 strings in process signals

ansible/vars/ppc64le.yml
Changes powervs region to `syd05` from `mon01` to fix errors with Main collector CI vm creation.
Tested in CI.
=> Switch ppc64le cloud region to mitigate vm creation failures.

ansible/requirements.txt, ansible/requirements.yml, collector/lib/ProcessSignalFormatter.cpp, collector/lib/Utility.cpp, collector/lib/Utility.h, collector/test/UtilityTest.cpp
Backport of #1857 
(needed #1837 as well to successfully spawn VMs)
=> ROX-26025: Backport UTF-8 sanitizing fix for 4.5

ansible/group_vars/all.yml
cos-beta started to fail on 3.19/4.5, and this was patched on master.
Also re-enable cos-dev in the meantime.
=> Backport cos and rhel-sap verifier issues

ansible/group_vars/all.yml
Simply adding Ubuntu 24.04 to the list of VMs used in our integration tests.
=> Add Ubuntu 24.04 to the VMs used during testing

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/EnvVar.h, collector/lib/NetworkStatusNotifier.cpp, collector/lib/NetworkStatusNotifier.h, integration-tests/container/schedule-curls/schedule-curls.sh
Original motivation for this PR was to narrow down a flake we've been having with some of the afterglow tests. However, in order to make it easy to add the log messages, the RunSingle and RunSingleAfterglow methods have been unified, since their difference was minimal.
Unrelated to this, the HandleAfterglowEnvVars method has been slightly rewritten to make its workflow more streamlined and easier to follow.
=> Refactor RunSingle and RunSingleAfterglow into a single method

collector/container/devel/install.sh, collector/container/konflux.Dockerfile, collector/container/rhel/install.sh
Reasoning for removing each package:
- kmod has not been needed since we stopped supporting kernel modules
- libyaml and libarchive have vulnerabilities, are unused by the the collector binary and show no other package depend on them when querying with rpm.
- Replaced `xargs rpm -e` with the method used in konflux.Dockerfile, so findutils is no longer needed either.
=> Remove unneeded packages from final collector image

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/test/CollectorConfigTest.cpp
Includes support for enabling/disabling external IPs based on runtime config, deferring to existing feature flag if none is provided
In subsequent PRs, the runtime configuration will be populated. 
~- [x] Updated documentation accordingly~
Unit tests added to exercise the intended behaviour. It is not possible to integration-test this until Sensor->Collector communication has been built.
=> ROX-26344: adds runtime configuration to collector

ansible/vars/ppc64le.yml
Backport #1859 on release-3.19 to hopefully restore Power VMs creation and thus integration-tests.
=> Backport on 3.19: Switch ppc64le cloud region

.github/workflows/integration-tests-vm-type.yml, Makefile, ansible/roles/run-test-target/tasks/test-collection-method.yml, integration-tests/Makefile, integration-tests/pkg/collector/collector_docker.go, integration-tests/pkg/common/utils.go, integration-tests/pkg/executor/executor.go, integration-tests/pkg/executor/executor_docker_api.go, integration-tests/pkg/mock_sensor/server.go, integration-tests/suites/base.go, integration-tests/suites/perf_event_open.go
Some flakes we have in CI may be due to errors on the auxiliar containers we run alongside collector. In order to make it easier to debug this type of flakes, container logs could be used to get more information on what is going on.
=> Capture logs for all containers used in tests

.github/workflows/integration-tests-vm-type.yml
Doing this makes the artifacts easier to use, since it doesn't require unzip and unarchiving the logs separately. It also fixes an error with the benchmark steps, since these expect the perf.json files to be readily accessible.
Unfortunately, I wasn't able to do this in ansible, so running the test manually on remote systems still creates archives on the local host.
=> Unarchive log files before uploading artifacts

collector/lib/Logging.cpp, collector/lib/Logging.h
Adding the number of times a log message has been throttled can add value in the sense that having the message show up once or twice may not be as worrisome as it showing up thousands of times.
In order to achieve this, the log message can be split between its header and the actual message. The header will now be handled by classes separate to LogMessage that will hold the information necessary to print them and use a common ILogHeader interface. This is done in order to reduce the amount of code necessary in macros, there shouldn't be a huge performance difference, but the current approach might take a bit more memory in order to store this data, some testing is needed. Calling virtual methods for printing the header could also have a performance impact, but given we don't print that …
=> Output the number of times a log has been throttled

collector/lib/CollectionMethod.cpp, collector/lib/CollectionMethod.h, collector/lib/CollectorArgs.cpp, collector/lib/CollectorArgs.h, collector/lib/CollectorConfig.cpp
When read from an environment variable, the collection method was not being canonicalized, leading to failing to parse it when the collection method was in uppercase. Moved the canonicalization logic to a ParseCollectionMethod and used that on args and environment variables.
=> Fix parsing collection method from environment variables

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/test/CollectorConfigTest.cpp, docs/references.md
The protobuf definitions for collector config were changed here https://github.com/stackrox/stackrox/pull/12972
This makes use of the updated protobuf definitions. The changes impact the code to read the configuration, associated tests, and documentation.
The following is an example of how the config file has changed
```
networkConnectionConfig:
enableExternalIps: true
```
```
networking:
externalIps:
enable: true
```
ACS was deployed on a GKE cluster using a commit from https://github.com/stackrox/stackrox/pull/12972 
A config map with the following contents was created
```
apiVersion: v1
kind: ConfigMap
metadata:
name: collector-config
namespace: stackrox
data:
runtime_config.yaml: |
networking:
externalIps: …
```
=> ROX-26578: Improvements to CollectorConfig protobuf definitions

.tekton/collector-build.yaml
Let the Konflux team manage these resources as they seem to be on track of doing that
https://github.com/konflux-ci/build-definitions/pull/1247
No automated tests.
Only CI.
=> build: Drop clamav-scan resource requests

.tekton/collector-component-pipeline.yaml
Add new required task to pipeline. 
> The task should run after the build-container task and assign its IMAGE_URL and IMAGE_DIGEST results to the tasks parameters.
- ~[ ] Updated documentation accordingly~
- ~[ ] Added unit tests~
- ~[ ] Added integration tests~
- ~[ ] Added regression tests~
No new tests required. Konflux CI pipeline passes.
=> ROX-26528: add rpms-signature-scan task to pipeline

collector/lib/CollectorConfig.cpp, docs/references.md
Let's start to converge on a normalized feature-flag naming: `ROX_COLLECTOR_<feature>_<option>`
This PR is only about the name of the env-var (and updating the associated doc). The code is not touched.
=> Rename the external-IPs feature-flag [ROX_COLLECTOR_EXTERNAL_IPS_ENABLE]

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/CollectorService.cpp, collector/lib/NetworkStatusNotifier.cpp, collector/test/CollectorConfigTest.cpp, docs/references.md
Makes it so that when the ConfigMap or config file is updated collector reads it and updates the runtime configuration. Also handles cases were the ConfigMap does not exist at collector startup, is created later, and is deleted during runtime.
Deployed ACS on a GKE cluster using `deploy/deploy-local.sh`. Replaced the collector image with one from this PR. The connection reported by collector to sensor where logged. Initially there was no ConfigMap. 
Before deploying ACS the following deployment was created
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: external-dns
spec:
replicas: 2
selector:
matchLabels:
app: external-dns-app
template:
metadata:
labels:
app: external-dns-app
spec:
containers:
- name: …
```
=> ROX-26637: Reread configmap when it is updated

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/ProcessSignalFormatter.cpp, collector/lib/ProcessSignalFormatter.h, collector/lib/ProcessSignalHandler.h, collector/lib/system-inspector/Service.cpp, collector/test/ProcessSignalFormatterTest.cpp
Add an internal option to not collect process arguments, as a workaround for [ROX-25845](https://issues.redhat.com/browse/ROX-25845).
Previous evaluation in the field with the debugging image.
=> Allow to ignore process arguments

integration-tests/pkg/executor/executor_docker_api.go, integration-tests/pkg/executor/retry.go
TestProcessListeningOnPort has became flaky in a nasty way, leaving no logs
from the flask container. Most likely reason is that it takes some time to
start the container, while the client method ContainerCreate doesn't wait for
"running" status.
Make the test more robust by waiting until it reports running status. It's been
done using ContainerExecInspect, not ContainerWait, because the latter one
isn't suitable despite the name. ContainerWait [[1]] could only wait for a
non-running state, and is designed to wait until a container has finished it's
job.
[1]: https://pkg.go.dev/github.com/docker/docker/client#Client.ContainerWait
Manual testing, running the flaky test.
=> Wait for a container to be running

.tekton/collector-build.yaml
Occasionally, I saw `determine-image-tag` failing at `use-trusted-artifact` with OOM. I don't have a working link handy but I think this was the reason for https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/collector-build-gw9zk to fail because https://github.com/stackrox/collector/runs/31840930570 shows this:
Note the following in the failure snippet
> Using token for quay.io
it is what gets logged in `use-trusted-artifact` step, e.g.
There's something special about collector repo that it requires more memory for dealing with TAs.
Failures happen sporadically which I attribute to clusters getting loaded by other tenants and then containers get less memory than `limits` (because OOTB in Konflux `requests` < `limits`).
It's a bit of a question …
=> build: Prevent OOM kills around Collector TAs

collector/lib/system-inspector/Service.cpp
Bumping Falco to version 0.18.1 and fixing some compilation errors for our code to be compatible with it.
The new branch can be inspected at [this branch](https://github.com/stackrox/falcosecurity-libs/tree/0.18.1-stackrox) or in this [draft PR](https://github.com/stackrox/falcosecurity-libs/pull/87), (unfortunately, this last one is showing more style changes than I'd like).
Small changes are needed in Falco for fixing compilation as well, so [this PR](https://github.com/stackrox/falcosecurity-libs/pull/88) needs to be merged before this one.
=> Bump Falco to 0.18.1

integration-tests/pkg/mock_sensor/server.go
This makes it so that the mock server for collector integration tests can handle external IP addresses and CIDR blocks. Currently the mock server can only handle the `AddressData` field of the `NetworkAddress` struct. However, for external IP addressed and CIDR blocks the `IpNetwork` field is used. This change is needed for testing runtime configuration and the external IPs feature. See https://github.com/stackrox/collector/pull/1899
The function modified here is used to convert objects of type `NetworkConnection` to `NetworkInfo`. In the future `NetworkInfo` will not be used and `NetworkConnection` will be used directly. The same will be done for all of the types in ` integration-tests/pkg/types`. See https://issues.redhat.com/browse/ROX-26716
If any of these don't …
=> ROX-26711: Collector mock server should handle external ips

Makefile
Podman has a bug in it which makes it so when using the --platform argument, it will ignore existing images in cache and always attempt to pull. This is particularly annoying when trying to test a change to the builder image, since running the start-builder target will:
- Build the image from source.
- Pull the image from quay.
- Run the image without the local modifications.
Removing the argument fixes the issue and it should have no major impact on developer workflow, since it is meant to be used locally anyways.
See: containers/podman#24420
=> Remove --platform from start-builder target

Makefile
Reverts stackrox/collector#1922
Turns out that argument is needed when building for multi-arch, I'll figure out a different way to work around the podman bug mentioned in the original PR.
=> Revert "Remove --platform from start-builder target"

.gitmodules, builder/install/30-cares.sh, builder/install/versions.sh
c-ares is added as a submodule in order to unify the way we handle dependencies for the collector builder image. It is also updated to the latest release version.
=> Add c-ares as a submodule and update to 1.34.2

.github/workflows/integration-tests.yml
Konflux always builds multi-arch images and manifests, so we might as well always test all of them.
=> Always run multi-arch tests for konflux builds

.tekton/determine-image-tag-task.yaml
- This enables tagged builds with `-fast` suffixes to unblock the work on <https://github.com/stackrox/stackrox/pull/13079>.
- Tag needs to be pushed before the branch as I make no attempt to tweak triggering CEL expression.
- This does not yet attempt to do the full release setup.
After merge:
Checked that:
=> ROX-26026: Make `determine-image-tag` recognize git tags

.tekton/determine-image-tag-task.yaml
See https://github.com/stackrox/collector/pull/1920
None.
Here will only check that CI is green.
=> ROX-26026: Backport #1920 git tags handling

.tekton/collector-build.yaml, .tekton/collector-component-pipeline.yaml
This cherry-picks the following PRs currently marked with `backport-for-4.6-konflux-release` label:
- https://github.com/stackrox/collector/pull/1913
- https://github.com/stackrox/collector/pull/1916
- https://github.com/stackrox/collector/pull/1932
No change.
Only Konflux CI.
=> build: Konflux cherry-picks for 3.20.3

integration-tests/integration_test.go
One of the expected endpoints in the ProfsScraper integration-test seems to be duplicated.
Remove it.
=> [integration-test] Remove a duplicated expected listening endpoint

.gitmodules, builder/Dockerfile, builder/install/90-bpftool.sh, collector/container/konflux.Dockerfile
Downstream builds with ubi 8, which ships a bpftool that is old and doesn't work with the latest Falco changes on Arm and Z. In order to circumvent this, we can simply build from source.
CI is enough.
=> Build bpftool from source

.tekton/collector-build.yaml
There are a couple of changes to the PipelineRun files:
* Update application and component names to match the ACS 4.6 release versions
* Update the CEL expression to only run ACS 4.6 pipelines on Collector 3.20 PRs and pushes. All PRs to the release-3.20 branch will trigger Konflux builds.
=> ROX-26784: Configure tekton pipelines for release branch

collector/lib/ConfigLoader.cpp, collector/lib/NetworkStatusNotifier.cpp
So this is embarrassing. The rate limit wasn't parsed from the config and copied over to the local runtime config object, which meant that the rate limit was set to zero and no network connections were sent from Collector.
This fixes that. It also adds some more useful logging around rate limiting.
Tested locally on OCP 4 cluster.
=> Rate limiting fixes (config parsing, better logging)

integration-tests/pkg/assert/assert.go, integration-tests/pkg/mock_sensor/expect_conn.go, integration-tests/pkg/mock_sensor/server.go, integration-tests/pkg/types/network.go
Currently the mock server only maintains a map where the key is a networking connection, instead of a full list of all connections that it sees, this means that if a connection is opened and closed multiple times it will only save the opening event once. For some tests all of the opening events will need to be recorded. For the runtime configuration tests the same connection will be opened and closed multiple times, so the changes here are needed for it. See https://github.com/stackrox/collector/pull/1899
This PR is built on another PR that makes it so that the mock server can properly handle connections involving external IPs and CIDR blocks. https://github.com/stackrox/collector/pull/1901
Other changes are also made. 
1. The addition of a function that requires that the elements of the …
=> ROX-26726: Collector integration tests should record all connections

.github/workflows/integration-test-containers.yml, .github/workflows/konflux.yml
Since konflux always builds multiarch images and we always try to test them, we should force the test container to build in multiarch mode. If we don't, then we get test failures on the konflux integration tests for PRs due to the tester image not existing.
=> Always build multiarch tests for the konflux workflows

ansible/roles/provision-vm/tasks/sles.yml
This fixes the SUSE fix, but first registering the VM which allows us access to the repo in which podman lives.
=> Register SLES VMs before installing podman

collector/lib/NetworkSignalHandler.cpp
Accept4 was ignored by the signal handler, resulting in missing connection information, as shown with recent berserker network stress testing. This PR adds the missing syscall. 
Tested on an openshift 4 cluster, using berserker.
=> Adds accept4 to NetworkSignalHandler

collector/lib/ConfigLoader.cpp, collector/test/ConfigLoaderTest.cpp, integration-tests/integration_test.go, integration-tests/pkg/assert/assert.go, integration-tests/pkg/collector/collector_docker.go, integration-tests/pkg/collector/introspection.go, integration-tests/pkg/mock_sensor/expect_conn.go, integration-tests/pkg/mock_sensor/server.go, integration-tests/pkg/types/runtime_config.go, integration-tests/suites/base.go, integration-tests/suites/k8s/config_reload.go, integration-tests/suites/k8s/namespace.go, integration-tests/suites/runtime_config_file.go
Integration tests for runtime configuration. The tests create various versions of the runtime configuration file and check that the configuration introspection endpoint returns the correct expected configuration.
Ran the integration tests locally 2,000 times without a failure using the following script
```
#!/usr/bin/env bash
set -eou pipefail
for ((i = 0; i < 2000; i=i+1)); do
echo "i= $i"
sudo -E make -C integration-tests TestRuntimeConfigFile
done
```
=> Jv integration tests for runtime config

integration-tests/suites/base.go, integration-tests/suites/runtime_config_file.go
On top of fixing the `AfterTest` method signature, a suite teardown has been added for removing the /tmp/collector-test directory, this is not strictly needed, but it's good practise to cleanup completely after all tests.
Run the `TestRuntimeConfigFile` locally and checked the directory and configuration files are properly cleaned up.
=> Fix RuntimeConfigFileTestSuite cleanups

Makefile
Currently running with podman without root is not possible, since selinux prevents mounting of the project source directory. Disable this limitation is enough.
Build Collector with builder using podman.
=> Allow to run builder with podman

.tekton/collector-build.yaml
Context: https://issues.redhat.com/browse/ROX-24530
See https://github.com/stackrox/stackrox/pull/13757
=> ROX-24530: let Konflux images expire after 13w

builder/Dockerfile
We pin clang and llvm versions due to bugs in certain versions, which we would like to skip (see [1], [2]). Bump them to 19.1.5 .
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2209635
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2211472
Multi-arch CI pass is sufficient.
=> Use newest clang and llvm

collector/lib/CollectorConfig.h, collector/lib/CollectorRuntimeConfigInspector.cpp, collector/lib/ConfigLoader.cpp, collector/test/CollectorConfigTest.cpp, collector/test/ConfigLoaderTest.cpp, collector/test/NetworkStatusNotifierTest.cpp, docs/references.md, integration-tests/pkg/assert/assert.go, integration-tests/pkg/types/runtime_config.go, integration-tests/suites/k8s/config_reload.go, integration-tests/suites/runtime_config_file.go
It was suggested in the [PR](https://github.com/stackrox/stackrox/pull/13419) to set collector runtime config via helm charts that `networking.external_ips.enable` should be changed to `networking.external_ips.enabled`. The protobuf definitions tend to use enabled rather than enable. The same is true for the helm charts. The boolean datatype should be changed to an enum. per_container_rate_limit should be changed to max_connections_per_minute.
Even if these are never set using helm or operator, it is still good to make these changes.
These protobufs are internal and the feature that uses them is in technical preview. The collector expects the field to be `enable` rather than `enabled` in the collector-config ConfigMap. Some customers may have this setting, but as stated earlier this is in …
=> ROX-27634: Improvements to CollectorConfig protobuf definitions

collector/CMakeLists.txt
This is needed to avoid verifier issue with socketpair_x, which we don't use anyway.
Manual testing on affected kernels.
=> Exclude socketpair prog

builder/install/40-grpc.sh
Restore the previously ignored warnings and add 'no-attributes'
=> [grpc] silence a few build warnings

builder/install/install-dependencies.sh
When building the third party dependencies, we use the nproc command to try and get as many parallel builds as possible running at once. This can bring problems on systems with large numbers of cores and not enough ram to come with them, so for those we provide the option of manually setting the number of parallel builds with an environment variable.
=> Cap parallelism of dependency building

collector/lib/CollectorConfig.h, collector/lib/ConfigLoader.cpp, integration-tests/pkg/collector/collector.go, integration-tests/pkg/collector/collector_docker.go, integration-tests/suites/base.go
It is important for customers to know what the current collector runtime configuration is. While this can be read from the ConfigMap, it is possible that some misconfiguration in the ConfigMap, will cause the actual runtime configuration to be something other than what the user expects. For this reason it is important to log the runtime configuration in collector. Also it may also be important to know the timestamp at which a certain runtime configuration was applied. A ConfigMap will not by itself preserve that history.
In addition to the change mentioned above, a bug is fixed, which made it so that for each test in  a group of tests in the same suite, separate collector log files are created. Currently in such cases each test overwrites the log file of the previous test. This change was …
=> ROX-27695: Collector runtime configuration should be logged

.github/workflows/collector-builder.yml, .github/workflows/collector.yml, .github/workflows/integration-test-containers.yml
The notifications should notify us when we fail to build the collector, builder, test or any of the QA images.
=> Add slack notifications for image build failures

.github/workflows/collector-builder.yml, .github/workflows/collector.yml
Collector build randomly started failing on ppc64le and arm64 with the following segfault message:
```
gmake[2]: *** [driver/modern_bpf/CMakeFiles/ProbeSkeleton.dir/build.make:673: driver/modern_bpf/copy_file_range.bpf.o] Segmentation fault (core dumped)
gmake[1]: *** [CMakeFiles/Makefile2:2035: driver/modern_bpf/CMakeFiles/ProbeSkeleton.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```
The error itself seems to coincide with an update to the GHA runner which updates the kernel:
- Last successful build: https://github.com/stackrox/collector/actions/runs/12890846039/job/36009468005
- Runner version: 20250105.1.0
- First failing build: https://github.com/stackrox/collector/actions/runs/12939264126/job/36091246392
- Runner version: 20250120.5.0
- Release notes for this …
=> Fix image build segfaults on QEMU

.github/workflows/collector.yml, ansible/README.md, ansible/ci-build-collector.yml, docs/how-to-start.md
Since we have deprecated *full* images from Collector, we now want to drop the -slim tag for all images, since all image flavours are now inherently slim.
This PR removes upstream slim image tagging from Collector.
There are sibling PRs, which I will list here as they become available, that remove slim image use in other areas (downstream builds and the main repo)
=> ROX-18384: remove slim images from upstream

.github/workflows/integration-test-containers.yml
We recently had to change the image being used by the setup-qemu action in order to fix some segmentation faults while building collector and builder images on ppc64le and arm64 architectures (#2018). Now we are seeing similar segfaults when trying to build the integration test containers, so we are bumping the version there as well in hopes that it will solve the issue.
=> Use newer QEMU on test containers builds

ansible/requirements.yml
Downgrades ansible `ibm cloudcollection` to `1.51.0` from the latest `1.71.2` since it introduces some breaking changes for ppc64le. This is a workaround till the automation is updated for the latest version.
Tested in CI.
=> Downgrade ibm cloudcollection to 1.51.0 to workaround failures on ppc64le

.tekton/collector-component-pipeline.yaml
Following #1963 and https://github.com/stackrox/stackrox/pull/13350 we no longer require -latest or -slim images for Collector
=> ROX-18384: removes slim and latest images from konflux build

.github/workflows/cpaas.yml
As the title specifies, we've started building Arm based images downstream, so we might as well extend our test matrix to include them.
This also fixes a discrepancy in naming now that `-slim` is no longer used.
=> Add arm64 to the test matrix for the downstream tests

docs/troubleshooting.md
We've struggled in the past with connectivity issues and lack of information from the GRPC library, e.g. it's hard to distinguish a timeout error from a certificate error -- Collector will just say "can't connect" in both cases.
Add a note about useful workaround for that with GRPC_TRACE environment variable into the troubleshooting section.
=> Add note about GRPC_TRACE

.github/workflows/lint.yml
The lint CI job has started failing because the go version required by the latest release of shfmt is higher than the one being installed on the fedora:40 image. We could bump the image, but for now I think pinning the shfmt version would lead to the least pain in the future.
CI is enough.
=> Pin shfmt version

Makefile
On systems where selinux is _enforcing_, docker/podman has to be told to set appropriate labels on the builder container to access the source tree from within the container.
It should be enough that the build succeeds.
=> Set selinux labels to share source directory with builder.

collector/collector.cpp, collector/lib/ConfigLoader.cpp, collector/lib/ConfigLoader.h, collector/lib/Logging.h, collector/test/CMakeLists.txt, collector/test/ConfigLoaderTest.cpp, collector/test/proto/test-config.proto, integration-tests/pkg/mock_sensor/server.go, integration-tests/suites/base.go
This change is based upon a toy project I have at https://github.com/Molter73/config-much.
The basic idea is to use the introspection and reflection APIs from protobuf to populate the runtime configuration structures, which should allow us to add new fields to our protobuf definitions and have them magically show up in our code to use.
This is an alternative implementation to #1993.
CI should be enough to ensure no behavioral changes have been introduced.
=> Use protobuf reflection for loading runtime configuration

collector/lib/CollectorService.cpp, collector/lib/CollectorStatsExporter.cpp, collector/lib/NetworkConnectionInfoServiceComm.cpp, collector/lib/SignalServiceClient.cpp, collector/lib/Utility.h, collector/lib/system-inspector/Service.cpp, collector/test/NetworkStatusNotifierTest.cpp
This is a small clean up, removing our home made implementation of MakeUnique (which was needed back when we were still on C++11) and replacing it with std::make_unique.
=> Replace MakeUnique with std::make_unique

collector/lib/ProfilerHandler.cpp, docs/troubleshooting.md, integration-tests/integration_test.go, integration-tests/pkg/collector/collector_docker.go, integration-tests/pkg/executor/executor_cri.go, integration-tests/suites/gperftools.go
When we removed the /module mount from the collector daemonset we inadvertedly broke the gperftool cpu profiler, since it was using that directory for dumping its output files. This patch moves the dump directory to /var/profiles, which will be a new emptydir mount on the collector daemonset.
A new test is also added to ensure the profiles still starts, stops and produces some output.
=> Fix CPU profiler

.github/workflows/unit-tests.yml, Makefile, collector/container/konflux.Dockerfile
When iterating on collector changes, waiting for the image build takes some time because we build the binary, then run the unit tests which also attempt to build the binary again and run the tests themselves. If we ask for the image to be built, we should only do the steps required to build the collector binary and creating the image, if we want to run unit tests, we have a separate target for it.
On CI, the unit tests are already being run as a separate step, so removing it from the image build should be a net win with no losses there.
=> Stop running the unit tests as part of the image build

collector/lib/NetworkSignalHandler.cpp, collector/lib/NetworkSignalHandler.h, collector/lib/ProcessSignalHandler.h, collector/lib/SelfCheckHandler.cpp, collector/lib/SignalHandler.h, collector/lib/system-inspector/EventExtractor.h
<details>
<summary>NetworkSignalHandler attempts to read int64_t from unaligned memory.</summary>
```
/go/src/github.com/stackrox/collector/collector/lib/NetworkSignalHandler.cpp:92:15: runtime error: load of misaligned address 0x7f181b9dcb7c for type 'const int64_t', which requires 8 byte alignment
0x7f181b9dcb7c: note: pointer points here
00 00 08 00 00 00 00 00  00 00 00 00 00 00 00 00  24 00 00 00 03 00 00 00  96 75 63 5c c4 ff 33 18
^
```
</details>
<details>
<summary>Wrong destructor being called for SignalHandlers.</summary>
```
==10821==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x604000011a90 in thread T0:
object passed to delete has wrong type:
size of the allocated type:   40 bytes;
size of the deallocated type: 8 bytes.
#0 0x7f182948d3cf in operator delete(void*, …
```
=> Fix two address sanitizer bugs

collector/lib/Utility.cpp
This is a small PR to prevent protobuf message serialization on the stdout clients when log level would discard the result.
This changed was triggered by this comment: https://github.com/stackrox/collector/pull/2063#discussion_r2030217477
Was not able to test this locally, help would be appreciated.
=> Prevent serialization in LogProtobufMessage if log level is not met

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/HostInfo.cpp, collector/lib/ProcfsScraper.h, collector/lib/Utility.cpp, collector/lib/Utility.h
This change simplifies the logic for GetHostPath, since std::filesystem::path provides a dedicated operator/ which is guaranteed to have the correct separator and use it properly when concatenating paths.
On top of this, some C-like operations have been changed to use their std::filesystem equivalent.
=> Use std::filesystem::path in GetHostPath

.github/workflows/lint.yml, ansible/requirements.yml, collector/lib/ProfilerHandler.cpp, docs/troubleshooting.md, integration-tests/integration_test.go, integration-tests/pkg/collector/collector_docker.go, integration-tests/suites/gperftools.go
Backport of #2038, #2055 and #2066
Those PRs address respectively:
- PowerVM provisioning failures for integration-tests
- linter error because of an shfmt upgraded dependency
- gperf failures in integration-test
=> Backport PowerVM+shfmt+gperf fixes on 3.21 (4.7)

.github/workflows/lint.yml, collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/CollectorService.cpp, collector/lib/GetStatus.cpp, collector/lib/GetStatus.h, collector/lib/HostInfo.cpp, collector/lib/HostInfo.h, collector/lib/NetworkConnectionInfoServiceComm.cpp, collector/lib/NetworkConnectionInfoServiceComm.h, collector/lib/Utility.cpp, collector/lib/Utility.h
The hostname for a given node is lazily loaded in the HostInfo and will outlast any other object attempting to use it. As such, we should try to avoid unnecessary copies and just call the GetHostname method of the HostInfo class.
The GetHostname function from our utilities has been turned into a static method of HostInfo so we can directly access it calling HostInfo::GetHostname(), otherwise we would need HostInfo::Instance().GetHostname() which is a bit too verbose.
=> Stop copying hostname

collector/CMakeLists.txt, collector/lib/CMakeLists.txt, collector/lib/CollectorConnectionStats.h, collector/lib/CollectorService.cpp, collector/lib/CollectorService.h, collector/lib/CollectorStats.h, collector/lib/CollectorStatsExporter.cpp, collector/lib/CollectorStatsExporter.h, collector/lib/NetworkStatusNotifier.cpp, collector/lib/NetworkStatusNotifier.h, collector/lib/ProcfsScraper.cpp, collector/lib/ProcfsScraper.h, collector/test/NetworkStatusNotifierTest.cpp
This change started out from the effort to unify the services used to communicate with sensor. While attempting to add an output object to the notifier it became apparent this class has some issues with ownership of its members, which in turn makes it a bit odd to extend and modify.
In order to alleviate the problem the following changes are introduced:
- The connection scraper is now owned by NetworkStatusNotifier.
- The communication channel for network info is now owned by NetworkStatusNotifier.
- Connection stats are now owned by NetworkStatusNotifier.
- Move ownership of the prometheus registry into CollectorStatsExporter.
- The process store is now owned by ConnScrapper.
- Refactor CollectorConnectionStats into its own file.
When stating "X is now owned by Y" it stands for X now is …
=> Refactor NetworkStatusNotifier

.github/workflows/collector-builder.yml, .github/workflows/collector.yml, .github/workflows/init.yml, .github/workflows/integration-tests.yml, .github/workflows/konflux.yml, .github/workflows/main.yml, .github/workflows/unit-tests.yml
Utilize newly added [arm64 runners](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/ ) for github actions.
* Build arm64 images natively instead of using QEMU in all workflows
* Make arm64 builds, unit-tests, and integration tests run alongside x86_64 **by default** on PR workflows. Build time performance is slightly faster on ARM so it shouldn't increase total time to finish PR steps.
* Split and refactored the builder image job into a local and remote version 
=> Use ARM GH action workflow runners for ARM builds

.github/workflows/collector-builder.yml, .github/workflows/collector.yml, .github/workflows/init.yml, .github/workflows/integration-tests.yml, .github/workflows/main.yml, .github/workflows/unit-tests.yml
exclude for ppc64le isn't working from https://github.com/stackrox/collector/pull/2084 
=> Revert GH arm changes

collector/lib/NetworkConnection.h, collector/test/NetworkConnectionTest.cpp
IsCanonicalExternalIp does not work on big endian systems like s390x. This change makes it so the check is always done in network endianness, effectively making it independent of the system. Change is only needed on IPv4 checks because IPv6 uses 64 bit integers filled with 1s, so endianness is irrelevant in that case.
Konflux run should pass.
=> Make IsCanonicalExternalIp independent of system endianness

.tekton/collector-build.yaml, .tekton/collector-component-pipeline.yaml
Announcement: https://groups.google.com/a/redhat.com/g/konflux-announce/c/NxOyzi8wGxo/m/QXRGc1QqCQAJ
Passing Konflux pipeline
=> ROX-29078: switch to per component service account

.tekton/collector-component-pipeline.yaml
Adds two more required tasks to the Konflux pipelines.
See description of https://github.com/stackrox/scanner/pull/1881 for validation. Note that EC may display erroneous results for required task presences.
=> ROX-28568: Add required tasks sast-shell-check and sast-unicode-check to Konflux pipelines

.tekton/collector-build.yaml
Saw OOMKill again in prefetch-dependencies in this task (with a "call stack"):
- https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs/taskruns/collector-on-push-jpqj8-prefetch-dependencies/logs
- https://github.com/stackrox/collector/pull/2128/checks?check_run_id=42536648131
- https://github.com/stackrox/collector/pull/2128
From `kubectl describe pod collector-on-push-jpqj8-prefetch-dependencies-pod`:
```
[...]
step-use-trusted-artifact:
[...]
State:          Terminated
Reason:       OOMKilled
Exit Code:    137
Started:      Tue, 20 May 2025 10:34:05 +0200
Finished:     Tue, 20 May 2025 10:35:18 +0200
Ready:          False
Restart Count:  0
Limits:
memory:  3Gi
Requests:
cpu:     20m
memory:  3Gi
[...]
```
Here I suggest giving it +1 more …
=> chore: Bump memory limit in TA download

.tekton/collector-build.yaml
This follows up on https://github.com/stackrox/collector/pull/2129. In that PR I bumped the memory from 3 to 4Gi, but that wasn't enough as I saw `sast-unicode-check` failing [here](https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs/pipelineruns/collector-on-push-4cnxr) with OOMKill.
```
$ kubectl describe pod collector-on-push-4cnxr-sast-unicode-check-pod
[...]
Containers:
step-use-trusted-artifact:
[...]
State:          Terminated
Reason:       OOMKilled
Exit Code:    137
Started:      Wed, 21 May 2025 04:43:24 +0200
Finished:     Wed, 21 May 2025 04:45:25 +0200
Ready:          False
Restart Count:  0
Limits:
memory:  4Gi
Requests:
cpu:     33m
memory:  4Gi
[...]
```
Again, I don't know if the current value is enough but we'll see if …
=> build(fix): Bump TA steps memory from 4 to 6Gi

.github/workflows/integration-tests.yml, ansible/group_vars/all.yml
Add integration test for COS arm64
CI passing is sufficient: https://github.com/stackrox/collector/actions/runs/15148620044/job/42590584829?pr=2096
=> Add arm64 Google COS integration test

.github/workflows/collector-builder.yml, .github/workflows/collector.yml, .github/workflows/init.yml, .github/workflows/integration-tests.yml, .github/workflows/main.yml, .github/workflows/unit-tests.yml, ansible/group_vars/all.yml
**Undo the revert with a fix for error of using a runtime computed value within a job matrix.**
Re-enable changes from https://github.com/stackrox/collector/pull/2084 which was reverted. Now with fixes to github actions on these [commits](https://github.com/stackrox/collector/pull/2106/files/aa714121e95a525f5cde83e4b849ad80549124eb..baddaf52b967c30d66eb1965a22eae1e5ea941c2 )
**Original Description:**
Utilize newly added [arm64 runners](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/ ) for github actions.
* Build arm64 images natively instead of using QEMU in all workflows
* Make arm64 builds, unit-tests, and integration tests run alongside x86_64 **by default** on PR workflows. Build time performance is …
=> ROX-29116: (fix) Use ARM GH action workflow runners for ARM builds

.github/workflows/integration-tests.yml, ansible/group_vars/all.yml, ansible/group_vars/platform_rhcos_arm64.yml
Adds 4.12, 4.15, and 4.18 OCP versions of RHCOS to ARM integration tests.
(based on arm64 runners in https://github.com/stackrox/collector/pull/2084 for faster build)
✅ CI tests of RHCOS arm64 pass
=> ROX-28839 - Add RHCOS images to ARM integration tests

.github/workflows/k8s-integration-tests.yml, .github/workflows/konflux.yml, .tekton/collector-build.yaml
Per title and ticket. Updated https://issues.redhat.com/browse/ROX-27060 to leave a note about collector-slim for 4.6 backporting. Also updated running GHA integration tests on Konflux images.
Only CI.
=> ROX-29479: Use custom repos for Konflux built product

utilities/gardenlinux-bumper/bumper.py, utilities/gardenlinux-bumper/requirements.txt
Garden Linux changed how it names its GCP images, so we cannot get that
from the assets of a release directly. Instead, we need to parse the
markdown text on the release itself and get it from there.
=> Fix Garden Linux Bumper

.github/workflows/release.yml
Our current configuration forbids GHA from pushing branches and tags to our repos. This change uses the rhacs-bot token, which should have the required permissions
=> Fix token used for pushing of tags and branches in release workflow

.tekton/collector-build.yaml, collector/container/konflux.Dockerfile
This should resolve issues preventing CI in https://github.com/stackrox/collector/pull/2157 to succeed.
Please review this change by commits.
No change.
Only CI.
=> build: Fix Konflux builds

.github/workflows/integration-test-containers.yml, .github/workflows/integration-tests-vm-type.yml, .github/workflows/k8s-integration-tests.yml, ansible/roles/run-test-target/tasks/test-collection-method.yml, integration-tests/Makefile
=> Move the collector tests image to its own registry (#2150)

.tekton/collector-build.yaml, .tekton/collector-component-pipeline.yaml, collector/container/konflux.Dockerfile, rpms.lock.yaml
The list of commits to add into the branch was retrieved with the following command:
```sh
git log --oneline release-3.22...master -- rpms.* .tekton .konflux .github/workflows/konflux.yml collector/container/konflux.Dockerfile
```
The commits were then cherry-picked by reverting the list in neovim like this:
```vim
.! git log --oneline release-3.22...master -- rpms.* .tekton .konflux .github/workflows/konflux.yml collector/container/konflux.Dockerfile
g/^/m0
```
Then changed all the lines to keep only the sha and the `git cherry-pick` command with a macro.
CI builds konflux images and runs tests on them correctly.
=> Backport konflux changes to 3.22 (stackrox 4.8)

ansible/group_vars/all.yml
RHEL SAP 8.4 was removed from GCP, so we are using this opportunity to update the list of VMs used for testing.
CI is enough.
=> Update RHEL SAP VMs for tests

.github/CODEOWNERS
Per title.
Triggered by 
No testing possible.
=> fix: add rhacs-bot to CODEOWNERS for auto-approve targets

.github/renovate.json5
After https://github.com/stackrox/collector/pull/2197, we're seeing the first Renovate PRs being auto-approved: https://github.com/stackrox/collector/pull/2213
However, they don't auto-merge yet. Our [agreement](https://docs.google.com/document/d/1YiIA9cqZzBIqBr54_b9NViUGvTSou0rdjF5oh5Ag_sI/edit?tab=t.0#bookmark=id.ru7qfcc9qfp4) was to enable platformAutomerge, this is what this PR now does.
I allowed the auto-merge to be enabled in this repository.
Ran local Renovate validation.
=> chore: enable platform automerge for Renovatebot

.tekton/collector-build.yaml
With our current CEL expression, transitioning a PR from draft to ready will re-trigger a konflux build. This wouldn't be such a big deal, except those builds take about 30 minutes and block us from merging PRs, so a draft PR with a list of green CI checks and the required approvals will still need at least 30 minutes before being merged. This is worsened by the fact that konflux builds are currently flaky and can require multiple runs before getting a successful one.
With this change, this transition should no longer trigger a build.
=> Stop triggering konflux builds on marking PR as ready for review

.github/CODEOWNERS, .github/renovate.json5, .github/workflows/auto-approve.yml
Backporting the changes to the Renovate config, auto-approve workflow and CODEOWNERS.
This will enable auto-merges of Renovate updates to the release branch.
Tested in `master` branch, example https://github.com/stackrox/collector/pull/2223
=> backport(release-3.20): Renovate bot auto-merge

.github/CODEOWNERS, .github/renovate.json5, .github/workflows/auto-approve.yml
Backporting the changes to the Renovate config, auto-approve workflow and CODEOWNERS.
This will enable auto-merges of Renovate updates to the release branch.
Tested in master branch, example https://github.com/stackrox/collector/pull/2223
=> backport(release-3.21): Renovate bot auto-merge

.github/renovate.json5
I had added the additional labels to always rebuild the builder image and test container on the release branches, but that had no effect - PRs were opened without them and I had to add them manually: https://github.com/stackrox/collector/pull/2236.
So, it seems like Renovate is taking the configuration from master branch and applying it to all branches 🤷 
No testing required.
=> Add labels to Renovate PRs

.github/workflows/collector-builder.yml, .github/workflows/collector.yml, .github/workflows/init.yml, .github/workflows/integration-test-containers.yml, .github/workflows/integration-tests.yml, .github/workflows/main.yml, ansible/ci-build-builder.yml, ansible/ci-build-collector.yml, ansible/ci-build-tests.yml, integration-tests/Dockerfile, integration-tests/Makefile
=> Use P and Z GHA runners (#2215)

collector/lib/NetworkStatusNotifier.cpp
Currently two log messages are at debug level, which makes this level useless, since information in it is covered by an avalanche of repeating network status notifier messages. Downgrade to trace.
Run Collector manually with the new level.
=> Downgrade network status notifier messages to trace

ansible/vars/s390x.yml
Move ibmcloud region to us-east from toronto for s390x, due to capacity issues in the toronto region
=> Swaps ibmcloud region to us-east for s390x

.tekton/collector-component-pipeline.yaml
Looking at these earlier runs ([one](https://github.com/stackrox/collector/runs/49375296007), [two](https://github.com/stackrox/collector/runs/49487466713), [three](https://github.com/stackrox/collector/runs/49470441288)), buildah* tasks for `arm64` take one hour whereas other arches complete in 20-35 minutes. Thus `arm64` is solely responsible for slowing down the overall pipeline.
Similar to <https://github.com/stackrox/stackrox/pull/16654>, I apply here bigger instance type for arm64 to speed it up.
* `linux-cxlarge/arm64` ->
* 39m55s https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs/pipelineruns/collector-on-push-bhtn4
* `linux-c2xlarge/arm64` ->
* 27m12s https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/a …
=> build: Speed up `arm64` Konflux builds

ansible/scripts/fetch_ocp_rhcos_bootimage.sh
Recently we have seen some errors in CI where retrieving the rhcos images fails. This patch makes it so `curl` retries 5 times to get the version before failing in an attempt to mitigate this sort of error.
CI is enough.
=> Retry querying rhcos version

.github/workflows/integration-tests.yml
Disable garden-linux:
- the kernel bumper is broken and difficult to fix (for more than a month)
- process-listening-on-ports tests are failing for a reason specific to garden-linux
Let's simply disable the tests.
=> ROX-30928: Disable garden-linux integration tests
