.circleci/test-scripts/baseline/compare-and-update-baseline.sh
CIRCLE_TAG variable could be unbound, handle this case correctly.
Tested condition from the script locally.
=> Handle CIRCLE_TAG

.circleci/dockerized-drivers/unify-images.sh, .circleci/dockerized-pull-cache-image/10-pull-cache-image.sh, collector/container/Dockerfile, collector/container/Dockerfile.ubi, kernel-modules/dockerized/Dockerfile, kernel-modules/dockerized/Dockerfile.squash
=> Update ubi image version

builder/install/10-protobuf.sh
We want to support podman as the container provider for the build process, and keep compatibility with Docker
The build image and collector builds fine with this patch
=> ROX-11192 the collector can be built using podman

.circleci/images/70-build-collector-slim-and-base-images.sh, .gitignore, .openshift-ci/build/Dockerfile.build_root, .openshift-ci/build/Dockerfile.create_bundle, .openshift-ci/build/Dockerfile.drivers, .openshift-ci/build/install-gcloud-sdk.sh, .openshift-ci/build/push-images.sh, Makefile, builder/install/50-luajit.sh, collector/container/Dockerfile.template
Migrate images job to Openshift CI
See above
=> ROX-11211-collector-ci-migration-images

.openshift-ci/build/push-images.sh, .openshift-ci/jobs/push-images/push-images.sh, .openshift-ci/jobs/push-images/registry_rw_login.sh
Trying to push the images created by Openshift CI to the appropriate repos.
See above
=> Rox 11580 collector ci migration push images

collector/test/ConnTrackerTest.cpp
Add more unit tests to exercise the handling of updating know networks while connections already exist.
=> More unit tests for public network updates

.circleci/gcloud-init/setup-gcp-env.sh, .circleci/kernel-module-build-failures-check/20-test-for-build-failures.sh, .openshift-ci/drivers/BLOCKLIST, .openshift-ci/drivers/build.Dockerfile, .openshift-ci/drivers/drivers.Dockerfile, .openshift-ci/drivers/fc36-base.Dockerfile, .openshift-ci/drivers/pre-build.Dockerfile, .openshift-ci/drivers/rhel7-base.Dockerfile, .openshift-ci/drivers/rhel8-base.Dockerfile, .openshift-ci/drivers/scripts.Dockerfile, .openshift-ci/drivers/scripts/gcloud-sdk-install.sh, .openshift-ci/drivers/scripts/kernel-splitter.py, .openshift-ci/drivers/scripts/lib.sh, .openshift-ci/drivers/scripts/pr-checks.sh, .openshift-ci/drivers/scripts/process-kernels.sh, .openshift-ci/drivers/scripts/push-drivers.sh, .openshift-ci/drivers/scripts/run-builders.sh, .openshift-ci/drivers/scripts/sanitize-drivers.py, RELEASED_VERSIONS, RELEASED_VERSIONS.unsupported, kernel-modules/build/build-kos, kernel-modules/build/build-wrapper.sh, kernel-modules/dockerized/scripts/get-build-tasks.sh, kernel-modules/dockerized/scripts/patch-files.sh
This PR holds all the necessary changes for OSCI to build kernel drivers, PR openshift/release#29021 holds the OSCI configuration side that goes with these changes.
Been running rehearses on the OSCI PR, testing various combinations of builds and seems to be mostly working. Any further problems that might show up after merge will be addressed in follow up PRs.
=> OSCI driver builds

builder/Dockerfile
There is a package that cannot be properly upgraded on the centos builder image. Using `--no-best` to fix. [[ref](https://fedoraproject.org/wiki/Changes/DNF_Default_Best)]
=> Fix builder package install

.openshift-ci/build/Dockerfile.build_root
The default user is now root (https://github.com/stackrox/rox-ci-image/pull/154). We cannot use sudo as root and root is now the default user in our builds.
=> user is already root

.openshift-ci/jobs/integration-tests/Dockerfile, .openshift-ci/jobs/integration-tests/run-integration-tests.sh
=> Fixes integration tests Dockerfile

.circleci/images/70-build-collector-slim-and-base-images.sh, .openshift-ci/build/Dockerfile.create_bundle, .openshift-ci/build/Dockerfile.latest, .openshift-ci/build/build-driver-cache.sh, .openshift-ci/jobs/push-images/push-images.sh, Makefile, collector/container/create-bundle.sh
=> Build full collector image with OSCI drivers

.openshift-ci/slack/notify-if-needed.sh, .openshift-ci/slack/notify.sh, .openshift-ci/slack/template, Makefile
Notify on failed integration tests & unit tests on the main branch.
Local testing of the script.
=> Add slack notifications

.openshift-ci/drivers/scripts/lib.sh, .openshift-ci/jobs/integration-tests/create-vm.sh, .openshift-ci/jobs/integration-tests/env.sh, .openshift-ci/jobs/integration-tests/envbuilder.sh, .openshift-ci/jobs/integration-tests/run-integration-tests.sh, .openshift-ci/jobs/integration-tests/teardown-vm.sh, .openshift-ci/jobs/update-support-packages/env.sh, .openshift-ci/jobs/update-support-packages/run.sh, integration-tests/executor.go, kernel-modules/support-packages/02-fetch-collectors-metadata.sh, kernel-modules/support-packages/04-create-support-packages.sh, kernel-modules/support-packages/run-all.sh
Migrating the update support packages job. See the corresponding PR in openshift/release https://github.com/openshift/release/pull/30786
See above
=> ROX 11950 collector ci migration update support packages

docs/release.md
Updated the release doc for osci.
=> Jv update release doc

.openshift-ci/slack/notify-if-needed.sh
Reuse lib.sh to correctly identify if the error has happened in a PR context.
=> Use common function to verify the branch

.openshift-ci/drivers/scripts/pr-checks.sh, .openshift-ci/drivers/scripts/push-drivers.sh, .openshift-ci/jobs/integration-tests/env.sh, .openshift-ci/jobs/push-images/push-images.sh, .openshift-ci/jobs/update-support-packages/env.sh, .openshift-ci/jobs/update-support-packages/run.sh, .openshift-ci/scripts/lib.sh
Normalizes secrets mount and ensures consistency between helper functions. Now normalised to /tmp/secret
~ - [ ] Added regression tests~
=> Normalize secrets mount to /tmp/secret

collector/lib/ProtoAllocator.h
This is a backport of the fix in https://github.com/stackrox/collector/pull/846
=> [3.11 service release] crash with ProtoAllocator overflow

collector/collector.cpp, collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/CollectorService.cpp, collector/lib/Diagnostics.h, collector/lib/FileDownloader.cpp, collector/lib/FileDownloader.h, collector/lib/FileSystem.h, collector/lib/GetKernelObject.cpp, collector/lib/HostHeuristics.cpp, collector/lib/HostInfo.cpp, collector/lib/HostInfo.h, collector/lib/LogLevel.cpp, collector/lib/LogLevel.h, collector/lib/Logging.h, collector/lib/NetworkStatusNotifier.cpp, collector/lib/ProfilerHandler.cpp, collector/lib/SysdigService.cpp, collector/lib/Utility.cpp
To better reflect the error conditions during collector startup, the logging has been refined and the startup procedure has been refactored. Also includes a diagnostic class to dump a diagnostic summary should any action fail.
An example of a typical log from a failing collector is now:
```
Collector Version: 3.11.x-69-gedbcfd4d2f-dirty
OS: Alpine Linux v3.14
Kernel Version: 5.10.109-0-virt
Starting StackRox Collector...
[INFO    2022/10/07 14:13:54] Hostname: 'alpine'
[INFO    2022/10/07 14:13:54] User configured logLevel=info
[INFO    2022/10/07 14:13:54] User configured scrapeInterval=2
[INFO    2022/10/07 14:13:54] User configured turnOffScrape=1
[INFO    2022/10/07 14:13:54] User configured collection-method=kernel_module
[INFO    2022/10/07 14:13:54] Afterglow is enabled
[INFO …
```
=> ROX-11447: update startup and refine logging

collector/lib/NetworkStatusNotifier.cpp
Disables afterglow for endpoints. Afterglow for networking events means that for connection that open and close frequently we only report the first time the connection opens and when it has been closed for a period of time greater than the afterglow period. See https://github.com/stackrox/collector/pull/481
Ports are not closed and opened frequently so afterglow is not needed for endpoints, however afterglow for endpoints complicates the processes listening on ports feature. That is why afterglow is being disabled for endpoints.
See checklist
=> Jv rox 13005 disable afterglow for endpoints

docs/how-to-start.md
Add instructions on how to build a debug enabled collector image and deploy it to a k8s instance for debugging with GDB.
This change only changes documentation.
=> Add docs on how to debug collector on k8s

.gitignore, CMakeLists.txt, Makefile, collector/Makefile
These are a few little changes I gathered over time and which should make life a bit easier.
- ~~[ ] Updated documentation accordingly~~ There doesn't seem to be any reference to `make tests`
=> Some dev-env enhancements

ansible/vars/all.yml, collector/lib/SysdigService.cpp, integration-tests/suites/common/collector_manager.go
Bump Garden Linux VM version used in our integration tests to the latest available.
=> Bump Garden Linux VM version

RELEASED_VERSIONS
=> Automatic update of RELEASED_VERSIONS file for Rox release 3.73.0

.github/drivers/mock-cache.sh, kernel-modules/BLOCKLIST
This PR is meant for follow up fixes after merging the driver builds to the master branch.
CI run should be enough.
=> Follow up PR for GHA driver builds

README.md
This is a small PR updating the README badges so they properly show the GHA results.
None needed, this is a docs only update 🙂
=> Update badges for GHA

RELEASED_VERSIONS
Created by OSCI https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-release-3.73-merge-push-and-release/1622582414725353472 
(at least in theory - as fixed for future versions)
=> Release 3.73.2/update released versions

collector/container/Dockerfile.template, collector/container/Dockerfile.ubi
Bumping the UBI images version.
Green CI should be enough.
=> Bump ubi 8.6 to 8.7

ansible/group_vars/all.yml
Bumping the image used for Garden Linux testing.
Green CI should be enough.
=> Bump Garden Linux VM to latest image

ansible/group_vars/all.yml
=> Bump Garden Linux VM

.github/workflows/check-drivers-failures.yml, .github/workflows/cpaas.yml, .github/workflows/integration-tests.yml, .github/workflows/notify-module-version.yml, .github/workflows/support-packages.yml
Just updates the messages in the GHA workflow with the new team name.
=> Fixes slack notification messages following team name changes

.github/workflows/check-drivers-failures.yml, .github/workflows/cpaas.yml, .github/workflows/integration-tests.yml, .github/workflows/notify-module-version.yml, .github/workflows/support-packages.yml
The ongoing chat workspace migration involves renaming and recreating the webhooks. This updates both.
For oncall notifications, we also move from a shared channel to a Collector specific one.
=> Update slack notification channels

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 3.74.0

.github/workflows/integration-tests-vm-type.yml, collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/Logging.cpp, collector/lib/SysdigService.cpp, integration-tests/README.md, integration-tests/suites/common/collector_manager.go
Adds configuration to the integration tests to enable it on demand, and removes other references around that point. 
Tested locally, with and without the variable.
=> Refactors COLLECTOR_SD_LOGGING to use TRACE log level

.adr/0001-btf-probes-support.md, .adr/0002-modern-probe-delivery.md
A new proposal to capture most of the discussions about BTF support for Collector. There will be another one for the probe delivery mechanism.
=> Add a BTF probes ADR

ansible/group_vars/all.yml, ansible/roles/create-all-vms/tasks/by-family.yml, ansible/roles/create-all-vms/tasks/by-image.yml, ansible/roles/create-all-vms/tasks/main.yml
Trivial PR to bump the rhcos image version and add one for Openshift 4.13
=> Bumps the RHCOS 4.12 version and adds 4.13 image

ansible/group_vars/all.yml
Adds RHEL 9 VM family.
In CI we trust.
=> Adds rhel-9 family to rhel VMs in ansible

ansible/group_vars/gardenlinux-image.txt
Update Garden Linux VM used for testing to the latest version.
=> Update Garden Linux VM

collector/lib/CollectorConfig.h
=> Jv enable processes listening on ports by default

.github/workflows/integration-tests-vm-type.yml, ansible/benchmarks.yml, ansible/integration-tests.yml, ansible/roles/run-test-target/tasks/main.yml
Since now it's merged, test core_bpf collection method as well on a regular basis.
CI run is sufficient.
=> Run core_bpf integration tests unconditionally

ansible/README.md, ansible/benchmarks.yml, ansible/integration-tests.yml, ansible/roles/create-all-vms/tasks/main.yml, ansible/roles/run-test-target/tasks/main.yml, ansible/roles/run-test-target/tasks/test-collection-method.yml
Remove kernel modules from ansible playbooks.
CI is sufficient
=> Jv remove kernel module collection from integration tests

.adr/0001-btf-probes-support.md
Include self-checks details, heuristics hard-stop.
=> Adjust BTF adr

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.0.0

ansible/group_vars/all.yml
Disables SLES 12 testing temporarily.
=> Disables SLES-12 tests

collector/CMakeLists.txt, collector/Makefile, collector/container/Dockerfile, collector/lib/CollectorConfig.h, collector/lib/NetworkSignalHandler.cpp, collector/lib/NetworkSignalHandler.h, collector/lib/SelfCheckHandler.cpp, collector/lib/SelfCheckHandler.h, collector/lib/SelfChecks.cpp, collector/lib/SelfChecks.h, collector/lib/SignalHandler.h, collector/lib/SysdigService.cpp, collector/self-checks.cpp
Adds driver validating self-checks to collector. By spawning a process that performs some known actions, we can verify that the probe is working correctly by checking the stream of events from Falco.
=> Self-checks for driver verification

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 3.74.3

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/SysdigService.cpp
Backporting of https://github.com/stackrox/collector/pull/1186 and https://github.com/stackrox/collector/pull/1189
=> ROX-17553 Backport disable/control of the user-import feature

ansible/roles/run-test-target/tasks/test-collection-method.yml, integration-tests/README.md, integration-tests/go.mod, integration-tests/go.sum, integration-tests/images.yml, integration-tests/integration_test.go, integration-tests/suites/base.go, integration-tests/suites/benchmark.go, integration-tests/suites/common/collector_manager.go, integration-tests/suites/common/executor.go, integration-tests/suites/common/utils.go, integration-tests/suites/config/config.go, integration-tests/suites/config/env.go, integration-tests/suites/config/images.go, integration-tests/suites/connections-and-endpoints.go, integration-tests/suites/duplicate_endpoints.go, integration-tests/suites/listening_ports.go, integration-tests/suites/process_network.go, integration-tests/suites/procfs_scraper.go, integration-tests/suites/repeated_network_flow.go, integration-tests/suites/socat.go
Environment variables and configuration options now managed centrally rather than across the testing files.
Includes an image store, by way of a simple yaml file, to centralize the declaration of images between tests and avoid reuse.
Tested locally, otherwise depend on CI to exercise these changes.
=> ROX-15297: centralizes test configuration

integration-tests/suites/common/executor.go
Fixes check to disable selinux on fedora-coreos and rhcos
=> Fixes selinux disabling on coreos and rhcos

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.0.2

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.1.0

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.1.1

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.0.3

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.1.2

.github/workflows/collector-slim.yml
Adds s390x to CI build of collector slim
Testing in CI is sufficient
=> Add s390x to collector-slim multiarch build

kernel-modules/build/rhel9.Dockerfile
Add rhel9 dockerfile for building probes.  Necessary for building on s390x as centos 9 is first version avail on platform.  
For more details, ref the [Confluence page](https://stack-rox.atlassian.net/wiki/spaces/StackRox/pages/855998488/Proposal+Explicitly+List+Testing+Steps+on+PRs) about …
=> add rhel9 probe dockerfile

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.0.4

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 3.74.5

collector/lib/SelfChecks.cpp
=> Jv fix typo

.github/workflows/collector-full.yml, .github/workflows/cpaas.yml, .github/workflows/main.yml, ansible/ci-build-collector-full.yml
Multiarch builds are broken on CPaaS after merging #1271, this PR aims at fixing these workflows.
CI run: https://github.com/stackrox/collector/actions/runs/6083603998?pr=1314
=> Fix multiarch full image builds on cpaas workflows

integration-tests/Makefile, integration-tests/suites/config/images.go
Fixes issues where the QA tag was not set correctly for local testing.
Tested locally, and verified that images are pulled correctly.
=> Improves QA tag processing to better support local development

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 3.74.6

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.2.1

.tekton/collector-pull-request.yaml, .tekton/collector-push.yaml, rhtap.Dockerfile
=> RHTAP: fix workspace size for checkouts

.github/workflows/collector-full.yml, ansible/ci-build-collector-full.yml, kernel-modules/container/Dockerfile, kernel-modules/container/required-layers.py
Sometimes CI fails because the number of drivers we have changes compared to the number of layers they are split into when building the full image. This PR automates that calculation so that only the right layers are used.
=> Automate full image layer calculations

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.2.2

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.0.5

integration-tests/suites/common/utils.go, integration-tests/suites/connections_and_endpoints.go, integration-tests/suites/processes_and_endpoints.go, integration-tests/suites/types/endpoint.go
Adds a new test suite. The main purpose of the test suite is to test cases in which one command is run in one container. The processes and endpoints reported by collector are checked against expected processes and endpoints. Actual tests for the suite are being worked on here https://github.com/stackrox/collector/pull/1340
~~- [ ] Added unit tests~~
~~- [ ] Added regression tests~~
The actual integration tests are being added here https://github.com/stackrox/collector/pull/1340
Ran tests locally and in CI here  https://github.com/stackrox/collector/pull/1340
This is still being worked on, but the suite itself is working as intended.
=> Jv processes and endpoints integration test

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.1.5

.github/workflows/integration-test-containers.yml, ansible/ci-build-tests.yml
=> Ensures boolean type for build_multi_arch

.github/workflows/integration-test-containers.yml
Fixes integration test builds on master by ensuring that all multiarch test containers are built.
=> Include master (push) events when building multiarch test containers

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.3.0

integration-tests/integration_test.go, integration-tests/suites/common/utils.go, integration-tests/suites/gperftools.go
Make sure gperftool api is covered with an integration test. Note, that it's going to be performed only on supported platforms.
Local testing
=> Integration test for gperftool api

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.3.1

ansible/group_vars/all.yml, kernel-modules/BLOCKLIST
=> Reenables RHCOS 4.13 eBPF tests

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 3.74.8

.github/actions/job-preamble/action.yml, .github/workflows/support-packages.yml
Support package job seems to consume too much space. Before doing anything involved, try the easiest way and clean up some space.
=> Add a cleanup action

kernel-modules/BLOCKLIST
=> Block 6.8 kernels due to compilation issues

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 3.74.9

README.md, docs/how-to-start.md, docs/references.md, docs/roadmap.md
Profiling is in fact not a topic for "how to start", and already described in the troubleshooting. Roadmap never materialized in the documentation form, eventually we use other ways to define it. Ditto for glossary and supported systems.
=> Cleanup unused sections

RELEASED_VERSIONS
=> Update RELEASED_VERSIONS for StackRox release 4.3.5

.github/workflows/collector-slim.yml, ansible/ci-build-collector.yml
Switch to use Debug build type for PRs
=> Use Debug for PRs

.github/workflows/collector-slim.yml
Adds debug_mode to the native build ansible variables, to ensure it is defined.
=> Fix missing debug_mode variable in native builds

builder/Dockerfile, collector/lib/ProcessSignalHandler.cpp
Add systemtap into the builder to allow defining USDT, and add one to capture events when a new process was discovered.
=> Introduce USDT trace points

.github/workflows/check-drivers-failures.yml
=> Change notification for driver check failure

kernel-modules/BLOCKLIST
=> Expand block for RHEL kernels & mods

.github/workflows/gardenlinux-bumper.yml
`roxbot` is being retired in favor of `rhacs-bot`.
=> chore(CI): use rhacs-bot

ansible/ci-build-collector-full.yml
Fixes ansible to copy drivers into multiarch images, instead of just on x86
=> Fix ansible full build to ensure drivers are copied correctly

collector/container/konflux.Dockerfile
=> Remove drivers from Konflux images

ansible/group_vars/all.yml, ansible/roles/create-vm/tasks/create-ppc64le-vm.yml, ansible/vars/ppc64le.yml
Change ppc64le VMs' region from Osaka to Montreal.
=> Switch ppc64le cloud region

kernel-modules/support-packages/03-group-by-module-version.sh
=> Skip 2.10 support package build

.github/workflows/benchmarks.yml, .github/workflows/cpaas.yml, .github/workflows/integration-test-containers.yml, .github/workflows/integration-tests-vm-type.yml, .github/workflows/integration-tests.yml, .github/workflows/k8s-integration-tests.yml, .github/workflows/konflux-tests.yml, .github/workflows/main.yml
Builds the integration test image on demand, rather than for every commit.
=> Builds integration tests image on demand rather than for every commit

collector/lib/CollectorConfig.cpp, collector/lib/CollectorConfig.h, collector/lib/CollectorService.cpp, collector/lib/ConnTracker.cpp, collector/lib/ConnTracker.h, collector/test/ConnTrackerTest.cpp, docs/references.md
=> ROX-25218: [4.5] Instruct Collector to not aggregate some subnets

.github/workflows/benchmarks.yml, .github/workflows/collector-builder.yml, .github/workflows/collector.yml, .github/workflows/init.yml, .github/workflows/integration-tests.yml, .github/workflows/k8s-integration-tests.yml, .github/workflows/konflux.yml, .github/workflows/main.yml
Includes konflux workflow.
Primarily converting lots of checks from
event_name == push to event_name != pull_request
to account for schedule event.
Not entirely sure how to test this just yet.
=> Nightly CI for Collector

.tekton/collector-build.yaml, .tekton/collector-component-pipeline.yaml, .tekton/copy-subscription-manager-activation-key-oci-ta.yaml, .tekton/determine-image-tag-oci-ta.yaml
Based on main repo example: stackrox/stackrox#11616
=> ROX-25320: initial conversion to OCI artifacts

.tekton/collector-build.yaml
See https://github.com/stackrox/scanner/pull/1577
No changes to the automated tests.
If Konflux CI got triggered for this PR, the change works.
=> build: Add "appstudio" to the PR branch name filter for Konflux CI

.github/workflows/konflux-tests.yml, .tekton/collector-build.yaml, .tekton/collector-component-pipeline.yaml, collector/container/konflux.Dockerfile
=> ROX-20757: add multi-arch builds to konflux pipeline

.github/workflows/integration-tests-vm-type.yml, .gitignore
This publishes a friendlier report on GHA, which should make it a little easier to inspect failures on our integration tests.
It also removes the unused `COLLECTOR_OFFLINE_MODE` env variable, only because I saw it while working on this.
For an example on what the report looks like when a test fails, see: https://github.com/stackrox/collector/actions/runs/10317337453
CI is enough.
=> Add a test summary for the integration tests

.tekton/collector-build.yaml
Same as https://github.com/stackrox/scanner/pull/1593
Tested the same change in https://github.com/stackrox/scanner/pull/1593
=> build: Enable Konflux triggering in PR via label

.tekton/collector-component-pipeline.yaml
Recreates https://github.com/stackrox/collector/pull/1800 without formatting changes.
https://issues.redhat.com/browse/KONFLUX-3663 related.
No automated testing changes.
Only CI.
=> build: Upload SAST results

.github/workflows/integration-tests.yml, .github/workflows/main.yml, ansible/group_vars/all.yml, ansible/group_vars/platform_fedora_coreos_large_node.yml, integration-tests/integration_test.go, integration-tests/suites/ringbuf.go
A node with large number of CPU cores is an important edge case for Collector. Run integration tests on such a setup if requested expliciely or by schedule.
=> ROX-25477: Exercise integration tests on large nodes

collector/lib/system-inspector/Service.cpp
Bumping the Falco version on top of upstream 0.17.3 release.
=> Bump falco to 0.17.3-stackrox

.github/workflows/cpaas-sync-drivers.yml
=> Include hidden files for downstream driver failures artifact

.github/workflows/integration-tests-vm-type.yml, ansible/requirements.txt, ansible/requirements.yml
=> Pin ansible version to <2.17 to avoid loop bug

RELEASED_VERSIONS
=> Revert release 4.5.2 update

.tekton/collector-component-pipeline.yaml
See commit messages.
No automated testing contributions.
Only CI.
=> chore: Update Konflux pipelines

.tekton/collector-build.yaml
See https://github.com/stackrox/stackrox/pull/13101 for description.
No change to automated testing.
If Konflux CI gets sufficiently far, it's good enough.
=> build: Switch `git-url` from `repo_url` to `source_url`

integration-tests/pkg/executor/executor_docker_api.go
ContainerExecInspect is used for getting information about an exec command, not about a container. Using ContainerInspect should let us determine correctly if the container in question is running or not.
Additionally, propagate any errors from RetryWithTimeout to properly trigger test failures.
=> Use ContainerInspect for querying container status

.tekton/collector-build.yaml
Same as https://github.com/stackrox/stackrox/pull/13147 but for the collector repo.
Same as https://github.com/stackrox/stackrox/pull/13147, i.e. only making sure that Konflux build is happy before merge.
=> ROX-26765: Rename pipelineruns to enable on-push rerunning

.github/workflows/konflux.yml
Since we are preparing to use fast stream releases, we should start running integration tests on our tags for konflux builds.
=> Add tags to konflux tests

.gitmodules
Removing the googleapis submodule, since it is not being used.
Not needed.
=> Remove unused googleapis submodule

.tekton/collector-component-pipeline.yaml
Similar to https://github.com/stackrox/stackrox/pull/13194.
No change to automated testing.
Only CI.
=> build: Update Konflux pipelines

ansible/requirements.txt, ansible/requirements.yml
=> Pin ansible version to <2.17 to avoid loop bug (#1837)

.gitmodules, builder/Dockerfile, builder/install/90-bpftool.sh, collector/container/konflux.Dockerfile
Backport #1954 and the fixes needed in Falco.
=> Bump falco version

.gitmodules, builder/Dockerfile, builder/install/90-bpftool.sh, collector/container/konflux.Dockerfile
Backport #1954 and the fixes needed in Falco.
=> Backports for 6.11 verifier errors

collector/lib/ConfigLoader.cpp, collector/test/ConfigLoaderTest.cpp, docs/references.md
Straightforward rename, plus some extra tests and docs.
=> Renames per container rate limit, for consistency

.tekton/collector-component-pipeline.yaml
See the one in https://github.com/stackrox/stackrox/pull/13745
No change.
Passing Konflux CI should be sufficient.
=> chore: Kill `Java` mentions from Konflux pipelines

docs/release.md
Includes a considerations section to describe the reasoning
=> Removes annotation instructions from release docs

ansible/roles/provision-vm/tasks/redhat.yml
"Install needed utilities" step seems to be flaky, sometimes returning "No package Y available". Try to solve it with retries.
=> Experiment with adding retries

.tekton/collector-component-pipeline.yaml
See https://github.com/stackrox/konflux-tasks/pull/37
See https://github.com/stackrox/konflux-tasks/pull/37, and passing builds here.
=> ROX-27831: set image expiration based on event type and target branch

docs/references.md, docs/troubleshooting.md
Add a few lines about log level configuration.
Docs change.
=> Add documentation about log level

ansible/requirements.yml, ansible/roles/create-vm/tasks/create-ppc64le-vm.yml, ansible/roles/destroy-vm/tasks/destroy-ppc64le-vm.yml
Updates some ansible tasks for ppc64le in accordance with changes introduced in ibm cloudcollection v1.71.2 for powervs.
Tested in GHA.
=> Update ansible tasks for ppc64le

.github/workflows/release.yml, docs/release.md
This new workflow will enable people working in the collector repo to simply create a new release by issuing a workflow from the github actions tab. Two inputs can be provided to the workflow:
- version: Specify the <Major>.<minor> version to be tagged.
- dry-run: Run the workflow, create all tags but don't push to origin.
The intended usage is to make a first run with the dry-run flag on to check everything works as expected, then make a second run without the dry-run flag to create the release tags.
If the version input is left unchanged a new minor version will be tagged, creating the <Major>.<minor>.x tag on the master branch, setting up the release-<Major>.<minor> branch with an empty commit and the new .0 tag on top of said commit.
If a version is provided the behavior depends on …
=> Add a release workflow

collector/collector.cpp, collector/lib/HostInfo.h
=> Log host architecture at start-up

.github/workflows/integration-test-containers.yml, ansible/group_vars/all.yml
=> fix(ci): remove unsupported Ubuntu versions (#2175)

.github/workflows/integration-test-containers.yml, .github/workflows/integration-tests-vm-type.yml, .github/workflows/k8s-integration-tests.yml, ansible/roles/run-test-target/tasks/test-collection-method.yml, integration-tests/Makefile
Backport of https://github.com/stackrox/collector/pull/2150.
=> Move the collector tests image to its own registry (#2150)

.github/workflows/integration-test-containers.yml
=> Add a label forcing a test container rebuild on PRs (#2180)

.tekton/collector-build.yaml
Change the required suffixes to the konflux builds.
=> konflux: Add 4.6 suffix

.github/workflows/auto-approve.yml
Per title.
Fault: https://github.com/stackrox/collector/actions/runs/15918000419/job/44899131657?pr=2202
Manual testing in a non-git directory with 
```
$ cd /tmp
$ gh pr review 2202 --comment -b "interesting" --repo "stackrox/collector"
`
``
created https://github.com/stackrox/collector/pull/2202#pullrequestreview-2964921181
=> fix(ci): specify repository in auto approve workflow

.tekton/collector-component-pipeline.yaml
Same as https://github.com/stackrox/collector/pull/2241 but for `release-3.22`
No change.
Only CI.
=> ROX-30101: Revert MintMaker's reformatting / 3.22

ansible/group_vars/all.yml
=> Update RHEL SAP VMs for tests (#2214)
